### ISSUE TITLE
进阶>3监督学习>1.线性回归>9.平方绝对值误差--翻译

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#102]
## 课程导航+地址
进阶>3监督学习>1.线性回归>9.平方绝对值误差
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced-vip/parts/d8791027-d5b9-4ac3-922c-c68502706b13/modules/d1dd6eea-c2a7-421d-b1ce-7702c44aab31/lessons/c3bb570a-0e06-4cb3-b888-9c3e6e986ea2/concepts/6bc778b2-3c29-4b29-a59d-4522c9ae0f71

## 截图
![_20180912231635](https://user-images.githubusercontent.com/26052156/45434837-e626cf00-b6e1-11e8-8c4f-f38757ff341a.png)

![_20180912231445](https://user-images.githubusercontent.com/26052156/45434709-a364f700-b6e1-11e8-990e-b7a23c4a3849.png)

## 具体描述
视频1分15s处，结合上下文，这里的around表示在y-yhat周围加上了绝对值符号，而不是翻译说的约等于一个值的意思。结合上一句，“注意这里的表示”，建议改成类似：“我们在y-yhat两边用了绝对值符号” 。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
