### ISSUE TITLE
进阶>监督学习>1.线性回归>22正则化 --翻译

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#104]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced-vip/parts/d8791027-d5b9-4ac3-922c-c68502706b13/modules/d1dd6eea-c2a7-421d-b1ce-7702c44aab31/lessons/c3bb570a-0e06-4cb3-b888-9c3e6e986ea2/concepts/3f69dcbd-dc3b-4e6d-a1cc-3257db6ce3c0

## 截图

![_20180912234135](https://user-images.githubusercontent.com/26052156/45437508-83383680-b6e7-11e8-881f-0ee16441c60e.png)
![_20180912234402](https://user-images.githubusercontent.com/26052156/45437527-8af7db00-b6e7-11e8-9a82-27b63c4b7c6d.png)

## 具体描述
视频5分37秒处 differentiate 结合上下文意思 应该翻译成很难**求导/求微分** 而不是**区分**

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
