### ISSUE TITLE
4.非监督学习 > 课程 3：层次聚类法与密度聚类 >9.HC 示例与应用>课程资源链接

### ISSUE THREAD

**Issue by kinghonglee** [udacity/mlnd-issues-zh#107]
4.非监督学习 > 课程 3：层次聚类法与密度聚类 >9.HC 示例与应用>课程资源链接

## 截图
<img width="1212" alt="demo" src="图片地址">

![image](https://user-images.githubusercontent.com/31353264/38486412-8ec014a8-3c0f-11e8-912b-1b55cf1840ec.png)

## 具体描述
第二个资源链接能打开，但是内容没有了已经
：https://misuse.ncbi.nlm.nih.gov/error/abuse.shtml
![image](https://user-images.githubusercontent.com/31353264/38487013-5f03e38c-3c11-11e8-9a2e-774fb19b518a.png)

**Comment by UdacityShuwenLiu** [comment]
搞定
