### ISSUE TITLE
 2.机器学习基础>课程2 评估指标>混淆矩阵>翻译问题

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#112]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/e1850d27-a3d0-4a76-a021-1719ce34245f/concepts/2034dd12-8ffc-4753-b8f4-c6042487ea5d

## 截图
![default](https://user-images.githubusercontent.com/35166778/38500662-a6bb9d1a-3c3d-11e8-833f-8c7d32aacc44.png)
![default](https://user-images.githubusercontent.com/35166778/38500669-ac6dbea0-3c3d-11e8-8248-0f9519c398e4.png)

## 具体描述
第一张截图为练习提交后的视频，视频中提到的四种叫法为 真正、真负、假正、假负
但是在第二张截图，也就是练习当中的说明为真阳性、真阴性、假阳性、假阴性
翻译不一致，需要统一
建议：真阳性、真阴性、假阳性、假阴性统一更改为真正例、真负例、假正例、假负例

**Comment by nicoleliu42** [comment]
感谢反馈！已经统一翻译！
