### ISSUE TITLE
2.机器学习基础>课程2 评估指标>准确率>英文字幕与英文语音不对应（但中文字幕是对的）

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#115]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/e1850d27-a3d0-4a76-a021-1719ce34245f/concepts/f094bb62-02be-42e0-9803-8d0af1917f70

## 截图
![default](https://user-images.githubusercontent.com/35166778/38503935-fc3fe860-3c45-11e8-8c8d-2afaa038bee8.png)

## 具体描述
视频56s处开始，英文字幕与英文语音不对应，但是中文字幕是对的（很神奇。。。）

**Comment by nicoleliu42** [comment]
感谢反馈！已重新制作时间轴，正在部署中
