### ISSUE TITLE
 2.机器学习基础>课程2 评估指标>准确率2> 视频内容重复！

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#116]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/e1850d27-a3d0-4a76-a021-1719ce34245f/concepts/e8085600-b060-4486-adbb-f61b28a6fecc

## 截图
![default](https://user-images.githubusercontent.com/35166778/38504419-3bdec058-3c47-11e8-9474-475463ef63ff.png)
![default](https://user-images.githubusercontent.com/35166778/38504520-7882137a-3c47-11e8-9172-4146df8f768c.png)

## 具体描述
第一张截图为课程“准确率2”的内容，但是内容与“准确率”当中完成练习之后的视频内容完全一致。（见第二张截图）

**Comment by UdacityShuwenLiu** [comment]
已修复
