### ISSUE TITLE
2.机器学习基础>课程2 评估指标>假阴性与假阳性> 翻译不统一

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#117]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/e1850d27-a3d0-4a76-a021-1719ce34245f/concepts/93cb284f-09cc-459c-b65d-dd1593eda61c

## 截图
![default](https://user-images.githubusercontent.com/35166778/38505319-798eef8e-3c49-11e8-9d82-d46d29378750.png)
![default](https://user-images.githubusercontent.com/35166778/38505413-b0b6e2c8-3c49-11e8-930e-5c522ce4706e.png)

## 具体描述
如第一张截图，如果问题涉及的是医疗领域，那么翻译成假阳性或假阴性也是可以理解的，但是如果是其他领域（如第二张截图），假阳性或假阴性则不那么好，而且与之前的课程当中的中文翻译不统一。

**Comment by nicoleliu42** [comment]
感谢反馈！已经统一翻译！
