### ISSUE TITLE
 2.机器学习基础>课程2 评估指标>精度和召回率> 翻译不统一 + 课程结束界面问题 

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#118]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/e1850d27-a3d0-4a76-a021-1719ce34245f/concepts/72f25a6a-d6f7-4dcb-894d-cdad9b060c35

## 截图
![default](https://user-images.githubusercontent.com/35166778/38505817-b1ae9cf6-3c4a-11e8-87a4-bb3ea38a05cc.png)

## 具体描述
如图，课程名字为“精度和召回率”，但是在看完视频结束的界面的时候却显示“答案-假阴性和假阳性”，与课程名字不相同，并且在课程中同样遇到翻译不统一的问题。（12s,27s,34s,43s,1:00,1:03,1:11处字幕与之前课程不统一）

**Comment by nicoleliu42** [comment]
感谢反馈！已修改~

**Comment by nicoleliu42** [comment]
感谢反馈！已经修改~
