### ISSUE TITLE
2.机器学习基础>课程2 评估指标>精度> 翻译不统一 

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#119]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/e1850d27-a3d0-4a76-a021-1719ce34245f/concepts/dd22bf82-f166-4355-b53f-98c482f63699

## 截图
![default](https://user-images.githubusercontent.com/35166778/38506433-6bce5e68-3c4c-11e8-846b-0b2f39bf5cb6.png)

## 具体描述
视频10s处字幕假阴性，与之前的翻译假负例不统一（当然很多节课都是这样了，我都怀疑是不是应该直接改之前最开始的部分就OK了。。。）

**Comment by nicoleliu42** [comment]
感谢反馈 已统一为真正例、真负例、假正例、假负例 稍后会重新部署~！
