### ISSUE TITLE
强化学习  > 欢迎学习强化学习 > 1.简介 翻译问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#12]
## 课程导航+地址
进阶 > 强化学习  > 欢迎学习强化学习 > [1.简介](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/2942b8b9-76c1-451d-879c-3d31d3ac00c8/concepts/5241f281-16f4-47d5-9545-e992d4df889b#)

## 截图
<img width="659" alt="2018-04-06 12 54 59" src="https://user-images.githubusercontent.com/16119486/38404063-02ced398-399a-11e8-8633-e7798ec452f6.png">

## 具体描述
视频40s处字幕"力学"，需改为"动态分析"

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
