### ISSUE TITLE
中文翻译缺失

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#12]
## 课程导航+地址
例子：进阶 > 强化学习 > 强化框架 - 问题 > [2. 设置 - 回顾](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/cad3f391-a2a5-43d0-a340-6cf21442740b#)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/11350750/43581369-49beaf78-968b-11e8-9d73-19c6000d1cbc.png">

## 具体描述
视频1min07s处中文字幕缺失，需加上 “作为回应，智能体必须选择一个动作”

**Comment by sylviasun916** [comment]
已修改 感谢反馈
