### ISSUE TITLE
2.机器学习基础>课程3 模型选择>2.模型复杂度图表>需要梯子显现练习结果图表

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#122]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/eba65c23-416a-4876-bc82-3001ab152e32/concepts/5336629a-1eb2-4a56-a462-e3297d9827cf

## 截图
![default](https://user-images.githubusercontent.com/35166778/38513013-86a1f458-3c5f-11e8-8ea4-e6538e09175a.png)
![default](https://user-images.githubusercontent.com/35166778/38513018-8c91ef3a-3c5f-11e8-82af-0c9ddc86556e.png)

## 具体描述
完成练习过后，如果没有翻墙，则显示如第一张截图所示；如果翻墙，则显示第二张截图所示。需要梯子才能显现练习结果。

**Comment by UdacityShuwenLiu** [comment]
是的，需要翻墙才可以，这个暂时无解QAQ，需求已经提到美国区了QAQ
