### ISSUE TITLE
2.机器学习基础>课程3 模型选择>通过学习曲线检测过拟合和欠拟合>翻译问题+需要梯子显现练习结果图表 

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#123]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/eba65c23-416a-4876-bc82-3001ab152e32/concepts/c1d77b32-2c63-4cf3-ab9b-3c07470df57c

## 截图
![default](https://user-images.githubusercontent.com/35166778/38515129-ea39aaa0-3c65-11e8-9f6a-7f848a21ba4f.png)
![default](https://user-images.githubusercontent.com/35166778/38515226-32a0869c-3c66-11e8-81bc-7e3d3456248b.png)
![default](https://user-images.githubusercontent.com/35166778/38515231-36b71656-3c66-11e8-9ca9-f568ffa0b784.png)

## 具体描述
1.第一张截图是“测试运行”的翻译问题，与下面的按钮不一致，需改为“测试答案”
2.第二张截图是没有梯子的情况下，测试运行结果的截图；第三张截图是在翻墙的情况下，测试运行结果的截图，需要梯子才能显现出运行结果。

**Comment by nicoleliu42** [comment]
感谢反馈 翻译问题已修改 梯子的问题麻烦 @UdacityShuwenLiu 来看一下哦

**Comment by UdacityShuwenLiu** [comment]
显示图片的问题暂时无解，已经跟美国区反映了这个问题，感谢
