### ISSUE TITLE
6. 强化学习 > 课程4：动态规划 >7. 迭代策略评估>翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#126]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/9cc18f72-766e-433e-a764-46338e09cf79/concepts/cc964676-d852-4aa6-8fdf-e25b807fb037

## 截图
![image](https://user-images.githubusercontent.com/5260728/38526822-5cb49972-3c8a-11e8-82ed-5673aea34518.png)
![image](https://user-images.githubusercontent.com/5260728/38527010-49b16f98-3c8b-11e8-8a5b-ecba5ae17037.png)

## 具体描述
1. 2分8秒处，英文字幕“stop”应该为“step”
2. 4分45秒处，英文字幕“select”应该为“slack”

**Comment by nicoleliu42** [comment]
感谢反馈~已经修改英文字幕！
