### ISSUE TITLE
强化学习 > 欢迎学习强化学习 > 资源/参考指南

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#13]
课程导航+地址
例子：进阶 > 强化学习 > 欢迎学习强化学习 > [资源](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/2942b8b9-76c1-451d-879c-3d31d3ac00c8/concepts/e2c22bbc-590b-4ab5-96e1-fb4f99702c45)/[参考指南](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/2942b8b9-76c1-451d-879c-3d31d3ac00c8/concepts/181e6f13-658f-4783-8d86-46897dcfd83b)

## 截图
<img width="979" alt="2018-04-05 8 55 26" src="https://user-images.githubusercontent.com/16119486/38404758-dbdfb072-399e-11e8-8de1-2af448758cc4.png">
<img width="832" alt="2018-04-05 8 54 57" src="https://user-images.githubusercontent.com/16119486/38404700-8a8a5b00-399e-11e8-80c6-a330dd9b495a.png">

## 具体描述
教科书链接无法打不开或者非常非常非常慢

**Comment by LonerSkywalker** [comment]
### 更新
[http://go.udacity.com/rl-textbook](http://go.udacity.com/rl-textbook)
貌似很多地方都链接到这个地址 。 这个地址打开非常非常非常慢有时候无法打开

**Comment by UdacityShuwenLiu** [comment]
已修复
