### ISSUE TITLE
5.非监督学习>课程1.聚类>6.优化中心(橡皮筋) 翻译问题

### ISSUE THREAD

**Issue by thurm102** [udacity/mlnd-issues-zh#131]
## 课程导航+地址
非监督学习>课程1.聚类>6.优化中心(橡皮筋) > [练习：优化中心](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/bfc4f456-5bee-4c30-84a9-17559b08d0cb/modules/2ca706af-ae54-4219-907b-91ae5c3b110a/lessons/5452184060/concepts/30120086040923)

## 截图

<img width="952" alt="2018-04-10 11 59 20" src="https://user-images.githubusercontent.com/36925841/38535694-52ebd9b4-3cb7-11e8-9967-bc2f457a26b9.png">

## 具体描述

> 视频7s处字幕“第一个中心点的类”，需改为“第一个类的中心点”

**Comment by nicoleliu42** [comment]
感谢反馈！已经修改中文字幕，很快就会重新部署上线~
