### ISSUE TITLE
翻译不清晰

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#14]
## 课程导航+地址
例子：例子：进阶 > 强化学习 > 强化学习框架 - 问题 > [2. 设置 - 回顾](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/cad3f391-a2a5-43d0-a340-6cf21442740b#)

## 截图
<img width="1212" alt="demo" src="图片地址">
![image](https://user-images.githubusercontent.com/11350750/43581985-6ae4a12e-968d-11e8-98d2-311f92a17d5b.png)

## 具体描述
视频1m42s处字幕“我们不再称之为智能体接收观察结果”联合下句，需改为“此时，智能体接收的不再是观察结果，/ 而是环境状态”

**Comment by sylviasun916** [comment]
已修改 感谢反馈
