### ISSUE TITLE
强化学习 > 强化学习框架:问题 > 2.设置-回顾 翻译问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#14]
## 课程导航+地址
进阶 > 强化学习 > 强化学习框架:问题 > [2.设置-回顾](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/cad3f391-a2a5-43d0-a340-6cf21442740b#)

## 截图
<img width="349" alt="2018-04-06 1 40 00" src="https://user-images.githubusercontent.com/16119486/38404954-0812082e-39a0-11e8-8913-8aa06b4b4374.png">

## 具体描述
视频28s处字幕oral，需改为rl

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
