### ISSUE TITLE
5.深度学习>深度神经网络>7.Keras > 翻译

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#140]
## 5.深度学习>深度神经网络>7.Keras 
地址:https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/2f907351-912b-40c7-8b2b-289e1446fa32/concepts/7c3d9b4c-206d-4430-9459-c78357181d9a

## 截图
![layer](https://user-images.githubusercontent.com/26052156/38549866-9eea8a88-3ce7-11e8-8d94-e486004f1b13.png)

## 具体描述
* '层级'改为'层'
* 完全连接的层级 改为 '全连接层'

**Comment by nicoleliu42** [comment]
已修改 感谢反馈！
