### ISSUE TITLE
6. 强化学习 > 课程4：动态规划 >19. 截断策略迭代>翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#141]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/9cc18f72-766e-433e-a764-46338e09cf79/concepts/6437a70c-79eb-4968-99fa-cc32a1ebd7b4

## 截图
![image](https://user-images.githubusercontent.com/5260728/38562007-1cee896a-3d0c-11e8-8afe-6ab82e7d5c80.png)

## 具体描述
24秒处英文字幕“on a Bellman update role”有误，应为““on a Bellman update rule””

**Comment by nicoleliu42** [comment]
感谢反馈！已经修改英文字幕，很快就会重新部署~
