### ISSUE TITLE
5.深度学习 > 深度神经网络 > Keras > 代码与说明不符+翻译

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#142]
## 地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/2f907351-912b-40c7-8b2b-289e1446fa32/concepts/7c3d9b4c-206d-4430-9459-c78357181d9a
## 截图
![_20180410181456](https://user-images.githubusercontent.com/26052156/38551605-356f9dfa-3cec-11e8-91e1-4399711c87a7.png)
## 具体描述
* 所有"层级"改为"层 "
* "完全连接的层级" 改为 "全连接层"
*  代码中第一层是dense 下面说明是flatten.这里应该以代码为准.
## 截图
![verbose](https://user-images.githubusercontent.com/26052156/38551618-3d2bfa8e-3cec-11e8-9b35-5508bccd5873.png)

## 具体描述
* 这一整句建议改为: 然后使用fit命令训练模型并通过epoch参数来指定训练轮数(周期), 每epoch完成对整数据集的一次遍历. verbose参数可以指定显示训练过程信息类型.这里0表示不显示信息. 

## 截图
![_20180410221551](https://user-images.githubusercontent.com/26052156/38562682-b66c76e6-3d0d-11e8-8239-bb09c6dc5287.png)
## 具体描述
* Flatten()改为Dense()
* '输出宽度' 改为'输出维度'
* 总体来讲keras这块设计的不是很好
## 截图
![default](https://user-images.githubusercontent.com/26052156/38562957-541328d6-3d0e-11e8-9407-8fd34998479d.png)
## 具体描述
这个链接有时会打不开

**Comment by UdacityShuwenLiu** [comment]
已修复。
