### ISSUE TITLE
6. 强化学习 > 课程4：动态规划 >22. 值迭代>翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#143]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/9cc18f72-766e-433e-a764-46338e09cf79/concepts/e2746ec0-8816-4be3-9ab2-94da706ebc64

## 截图
![image](https://user-images.githubusercontent.com/5260728/38589671-fd0befcc-3d5e-11e8-95b2-581682ecd8eb.png)

## 具体描述
视频2分2秒处英文字幕“D of S”应该改为“V of S”

**Comment by nicoleliu42** [comment]
感谢反馈~已核实修改，正在部署中
