### ISSUE TITLE
6. 强化学习 > 课程4：动态规划 >21. 迷你项目：动态规划（第 5 部分）>翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#144]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/9cc18f72-766e-433e-a764-46338e09cf79/concepts/0dd9b1b9-ef53-4bad-b583-f31a15a09ac6

## 截图
![image](https://user-images.githubusercontent.com/5260728/38590269-b2f642a8-3d62-11e8-80e6-03f3d2b7fd06.png)

## 具体描述
截断策略迭代部分notebook中误写为5个参数，实际上是4个参数

**Comment by nicoleliu42** [comment]
感谢反馈！已在后台修改~！
