### ISSUE TITLE
5.深度学习>深度神经网络>22.Keras中的优化 > 链接

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#146]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/2f907351-912b-40c7-8b2b-289e1446fa32/concepts/ff0ab4d8-5441-4d00-baa3-88735b503b76
## 截图
![_20180411134509](https://user-images.githubusercontent.com/26052156/38598574-7d5a383e-3d8f-11e8-9932-447c985d4092.png)
## 具体描述
链接打不开

**Comment by UdacityShuwenLiu** [comment]
无法搬运至国内，已加上注释提醒学生
