### ISSUE TITLE
5.深度学习 > 深度神经网络 >keras lab 录取学生 > 代码

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#147]
## 课程导航+地址
教室地址：
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/2f907351-912b-40c7-8b2b-289e1446fa32/concepts/4d086d3f-17d5-4982-a5d7-595c6c1cd2e9

## 截图
![_20180411113525](https://user-images.githubusercontent.com/26052156/38598649-d8d5bdc8-3d8f-11e8-9518-3aedc803fea7.png)

## 具体描述
建议增加红框中代码，不然不能正常显示图片
## 截图
![_20180411120957](https://user-images.githubusercontent.com/26052156/38598679-f3f062d4-3d8f-11e8-8df2-6b159b8431f9.png)
## 具体描述
每个代码块下面多了一个执行结果，这个结果可以给学生提供参考。但它们不是markdonw而是代码块，不小心执行了就会报错显得比较混乱。建议修改成markdown模型或者去掉。

**Comment by UdacityShuwenLiu** [comment]
搞定 感谢
