### ISSUE TITLE
6. 强化学习 > 课程4：动态规划 >25. 知识检验>习题故障

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#148]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/9cc18f72-766e-433e-a764-46338e09cf79/concepts/ababe30b-5537-44cc-88ea-b0bfc178a494

## 截图
![default](https://user-images.githubusercontent.com/5260728/38598764-516d8982-3d90-11e8-8f80-91e7eef4a6be.PNG)

## 具体描述
在火狐浏览器上发现一个问题，习题中要求拖动填入的四个方块在某些位置上无法拖拽，要调整滚动条后才能拖拽

**Comment by UdacityShuwenLiu** [comment]
chrome上测试了一下没遇到相关问题，先close了哦～如果之后学生再次反映的话，会提给工程部，感谢

**Comment by leesper** [comment]
@UdacityShuwenLiu 不是chrome，是火狐啊！
