### ISSUE TITLE
5.深度学习 > 深度神经网络 >24神经网络回归 > 字幕公式

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#149]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/2f907351-912b-40c7-8b2b-289e1446fa32/concepts/5cb5938c-cf31-4749-88ca-32ee7b5f6bb2
## 截图
![_20180411135428](https://user-images.githubusercontent.com/26052156/38598862-b883c456-3d90-11e8-908e-73ba85468a64.png)

## 具体描述
1分08处 中英字幕的公式修改为与视频一样的公式

**Comment by nicoleliu42** [comment]
感谢反馈！这个在技术上暂时实现不了哦
