### ISSUE TITLE
翻译不准确

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#15]
## 课程导航+地址
例子：进阶 > 强化学习 > 强化学习框架：问题 > [7. 目标和奖励（第 1 部分）](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/891e84b2-aa82-4b52-aa19-60f7c9dca325#接)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/11350750/43588693-a345d8d2-969f-11e8-9898-a23ab22f7d35.png">

## 具体描述
视频49s处字幕结合点，需改为关节

**Comment by sylviasun916** [comment]
已修改感谢反馈！
