### ISSUE TITLE
5.深度学习 > 深度神经网络 > keras lab准备 IMDB > 翻译

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#150]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/2f907351-912b-40c7-8b2b-289e1446fa32/concepts/5e22aa8d-9d4d-4b83-8b34-9f606d0abee4
## 截图
![_20180411140343](https://user-images.githubusercontent.com/26052156/38599207-10bcfae2-3d92-11e8-9bca-f3023fafb459.png)
## 具体描述
论点含义改为 参数说明

**Comment by nicoleliu42** [comment]
感谢反馈！文本已经修正~
