### ISSUE TITLE
5深度>深度神经网络>28 keras lab > 翻译

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#151]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/2f907351-912b-40c7-8b2b-289e1446fa32/concepts/05134e3b-883e-4163-b821-49aa2f533c29

## 截图
![_20180411140959](https://user-images.githubusercontent.com/26052156/38599651-f9fa3f70-3d93-11e8-8c4a-07a2d167c92d.png)

## 具体描述
不同的图层 改为 不同类型的层(layer)
添加dropout 改为 添加 dropout层

**Comment by nicoleliu42** [comment]
谢谢反馈！已修正
