### ISSUE TITLE
5 深度 > 4 卷积 > 2cnn应用 > 翻译 +链接

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#153]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/52fc79a7-13ff-4065-b3c6-8203ec9ef60c/concepts/e7190f8c-c824-4936-89ff-db6230fd3d12

## 截图
![_20180411142955](https://user-images.githubusercontent.com/26052156/38600248-1c01386a-3d96-11e8-98fc-975e8cc0cef8.png)
![_20180411142612](https://user-images.githubusercontent.com/26052156/38600252-1cda1a86-3d96-11e8-8451-3e872e6d7efc.png)

## 具体描述
链接问题
## 截图
![rnn](https://user-images.githubusercontent.com/26052156/38600256-24514cee-3d96-11e8-8929-d399a4bf985d.png)
## 具体描述
视频41s处递归神经改为 循环神经

**Comment by nicoleliu42** [comment]
感谢反馈！这里的翻译暂时没有问题哦
麻烦 @UdacityShuwenLiu 看一下链接问题~ 谢谢~

**Comment by UdacityShuwenLiu** [comment]
@nicoleliu42 建议这里改成循环神经网络哦，是专业用语

**Comment by nicoleliu42** [comment]
@UdacityShuwenLiu 已修改~！
