### ISSUE TITLE
5深度>4卷积>5图片分类MLP> 翻译

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#155]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/52fc79a7-13ff-4065-b3c6-8203ec9ef60c/concepts/87712da9-5e20-4d75-b067-aa5f354e4a85

## 截图
![_20180411144457](https://user-images.githubusercontent.com/26052156/38600862-422efd36-3d98-11e8-8f2c-36bd719df512.png)

## 具体描述
35s最终完全连接层 改为 最后的全链接层

**Comment by nicoleliu42** [comment]
感谢反馈！字幕已经修正了哦 很快会重新部署
