### ISSUE TITLE
5深度>4卷积>11卷积层(2)> 中英字幕

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#157]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/52fc79a7-13ff-4065-b3c6-8203ec9ef60c/concepts/e6e271bf-d148-4e56-9320-04a07797f318
## 截图
![mlp](https://user-images.githubusercontent.com/26052156/38602276-dad2555c-3d9c-11e8-93b5-cc5dce1b338d.png)

## 具体描述
06:59处 NLP改为MLP

**Comment by nicoleliu42** [comment]
感谢反馈！已修正字幕 很快会重新部署~
