### ISSUE TITLE
5深度 > 4卷积 > 12 > 缺少阅读资料

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#158]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/52fc79a7-13ff-4065-b3c6-8203ec9ef60c/concepts/5d3711e1-601d-4b3c-a1d1-bcc2e267bbaa
## 截图
![_20180411152810](https://user-images.githubusercontent.com/26052156/38602643-f21fbe7e-3d9d-11e8-9018-32b3ee71fe95.png)

## 具体描述
缺少视频中提及的阅读资料

**Comment by UdacityShuwenLiu** [comment]
已经修复👍
