### ISSUE TITLE
5深度 > 卷积 > 15池化层 > 翻译

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#160]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/52fc79a7-13ff-4065-b3c6-8203ec9ef60c/concepts/65c0a599-ce95-4bfc-a00e-16d37e48a5cf
## 截图
![_20180411190101](https://user-images.githubusercontent.com/26052156/38614142-aae80180-3dbe-11e8-9ec9-c6fde9c64f14.png)
![_20180411190453](https://user-images.githubusercontent.com/26052156/38614147-adec2f78-3dbe-11e8-9139-1ea4574161d3.png)
![_20180411190527](https://user-images.githubusercontent.com/26052156/38614153-b01f9384-3dbe-11e8-8e32-05d0ee50fd98.png)
![_20180411191847](https://user-images.githubusercontent.com/26052156/38614154-b1a1e7a2-3dbe-11e8-97e2-14960edbe79e.png)
![_20180411191930](https://user-images.githubusercontent.com/26052156/38614156-b25c19b0-3dbe-11e8-923a-3107133ffc47.png)
![_20180411191807](https://user-images.githubusercontent.com/26052156/38614364-6fb863b0-3dbf-11e8-9b6d-708b7c445580.png)

## 具体描述
* 这里的stack 只是表示一堆参见后面视频出现的一摞煎饼,就是这个意思.并不是堆栈. 堆栈是heap和stack是两种. 请修改成一堆就好了

## 截图
![_20180411190359](https://user-images.githubusercontent.com/26052156/38614375-7e5ec328-3dbf-11e8-9e91-00458ec48369.png)
## 具体描述
02:20这里建议改为 **这是一种更极端的降低维度的池化类型.**

## 截图
![_20180411192256](https://user-images.githubusercontent.com/26052156/38614454-d0b054de-3dbf-11e8-8219-3aad646b97d4.png)
## 具体描述
这个比喻感觉并不能非常形象的解释Global Pooling layer. 如果可能建议增加一些补充资料 比如:论文network in network. 地址https://arxiv.org/abs/1312.4400 可以对keras的文档做一个补充吧.

**Comment by nicoleliu42** [comment]
感谢反馈！翻译问题已经修改 麻烦 @UdacityShuwenLiu 看看最后一个问题哦

**Comment by UdacityShuwenLiu** [comment]
搞定
