### ISSUE TITLE
5.深度 > 卷积 > 17图片分类CNN > 翻译+ 链接

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#161]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/52fc79a7-13ff-4065-b3c6-8203ec9ef60c/concepts/9cf863c1-e33a-41c8-a3de-43eb6e536071

## 截图
![_20180411215216](https://user-images.githubusercontent.com/26052156/38621824-44b62584-3dd4-11e8-92a4-f5277762b0ec.png)

## 具体描述
这个堆栈改为这些堆叠起来的层

## 截图
![_20180411215507](https://user-images.githubusercontent.com/26052156/38621852-5e6c4242-3dd4-11e8-8ee6-5897a6af0468.png)
![_20180411215523](https://user-images.githubusercontent.com/26052156/38621854-5f3cb9ae-3dd4-11e8-8103-99eeac44d2ca.png)

## 具体描述
完全连接 改为 全连接层

## 截图
![_20180411220015](https://user-images.githubusercontent.com/26052156/38621886-7c5790c2-3dd4-11e8-9265-9d5da132e9ee.png)
## 具体描述
链接打不开

**Comment by UdacityShuwenLiu** [comment]
链接问题已对学生加上注释提醒，麻烦 @nicoleliu42 解决一下翻译问题哦

**Comment by nicoleliu42** [comment]
感谢反馈 字幕已经修改！
