### ISSUE TITLE
5 深度 > 卷积 > 17aws gpu实例2 > 内容与云计算重复

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#162]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/52fc79a7-13ff-4065-b3c6-8203ec9ef60c/concepts/ced1fa22-5723-4212-b73f-08f7f6613cae

## 截图
![_20180411220150](https://user-images.githubusercontent.com/26052156/38622046-defc5f78-3dd4-11e8-8807-648a8e2a89cc.png)

## 具体描述
这部分与云计算有些重复,但是是值得注意的是 这里建议选用的实例是**p2.xlarge** 而不是云计算中介绍的**g2.xlarge**. 目前 p5和毕业项目用的比较多的是**p2.xlarge**. 建议按需调整

**Comment by UdacityShuwenLiu** [comment]
已对学生进行了提示，感谢
