### ISSUE TITLE
5.深度 > 卷积 > 19keras中的图片增强功能

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#163]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/52fc79a7-13ff-4065-b3c6-8203ec9ef60c/concepts/1a89db76-f327-43aa-b3f0-8fcceb561d68)

## 截图
![_20180411221159](https://user-images.githubusercontent.com/26052156/38622829-a10130d4-3dd6-11e8-8132-ca7f75c70847.png)

## 具体描述
1:50 不重要 改为 不可忽视

**Comment by nicoleliu42** [comment]
感谢反馈！已修改字幕 稍后会重新部署！
