### ISSUE TITLE
5 深度 > 卷积 >21可视化CNN 1 >链接

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#164]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/52fc79a7-13ff-4065-b3c6-8203ec9ef60c/concepts/86518a21-c85a-400b-a50c-8705ed93ca83

## 截图
![_20180411222855](https://user-images.githubusercontent.com/26052156/38623584-9f270228-3dd8-11e8-86ec-905f3cf30315.png)

## 具体描述
链接打不开

**Comment by UdacityShuwenLiu** [comment]
已经对学生作出提醒，感谢
