### ISSUE TITLE
5深度 > 4卷积  > 24keras中的迁移学习>链接

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#166]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/52fc79a7-13ff-4065-b3c6-8203ec9ef60c/concepts/dfe0e585-0a7b-45c4-bcee-8aa98d137d0f

## 截图
![_20180411224403](https://user-images.githubusercontent.com/26052156/38624466-b7121d62-3dda-11e8-8fbc-7b0c6f4197be.png)

## 具体描述
链接打不开

**Comment by UdacityShuwenLiu** [comment]
感谢，已提醒学生。
