### ISSUE TITLE
5深度 > 5癌症 >13练习敏感与特异 > 链接

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#168]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/54e18898-2666-445d-ba5c-ecab62a61d00/concepts/d825877c-3644-437b-8264-6bab8dc746df

## 截图
![_20180411230509](https://user-images.githubusercontent.com/26052156/38625717-aca56106-3ddd-11e8-827c-f7eff527da79.png)
![_20180411230526](https://user-images.githubusercontent.com/26052156/38625722-add3ee94-3ddd-11e8-864b-50046069f90b.png)

## 具体描述
链接提示订阅过期

**Comment by UdacityShuwenLiu** [comment]
已修复
