### ISSUE TITLE
5 深度>癌症 >18ROC曲线回顾 >链接

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#170]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/54e18898-2666-445d-ba5c-ecab62a61d00/concepts/536af98c-9002-4fe3-b6a1-4b02ce171a5a
## 截图
![_20180411232042](https://user-images.githubusercontent.com/26052156/38626809-ffe86be0-3ddf-11e8-8194-a44f273df878.png)

## 具体描述
链接显示未订阅

**Comment by UdacityShuwenLiu** [comment]
由于链接link到深度学习课程，目前已删去，不影响学生理解知识点
