### ISSUE TITLE
5深度 > 5癌症 > 24混淆矩阵回顾 >习题2答案存疑

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#171]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/54e18898-2666-445d-ba5c-ecab62a61d00/concepts/30493758-5ce5-4239-b206-309997c61932

## 截图
![_20180411233745](https://user-images.githubusercontent.com/26052156/38627756-5062f764-3de2-11e8-8905-76d66f77d540.png)
![_20180411233659](https://user-images.githubusercontent.com/26052156/38627760-51dbd1ce-3de2-11e8-9cbc-0f06dd6f79c7.png)

## 具体描述
根据题目描述该练习答案应该是0.6 但是提交错误 0.4是正确的. 同样的习题1就是正确的.

**Comment by UdacityShuwenLiu** [comment]
已修复，感谢建议
