### ISSUE TITLE
5深度 > 癌症 > 27 有用资源 > 链接

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#172]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/54e18898-2666-445d-ba5c-ecab62a61d00/concepts/23124cbb-77e8-4f8c-aaf4-c27b809c82ea
## 截图
![_20180411234512](https://user-images.githubusercontent.com/26052156/38628119-360cdc76-3de3-11e8-8aac-90beb0e05d36.png)

## 具体描述
打不开

**Comment by UdacityShuwenLiu** [comment]
感谢，已经为学生加上注释。
