### ISSUE TITLE
5 深度 > 6深度自我评估>练习>翻译

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#173]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/b5e20869-4174-4fbb-98dd-cb0e09fc9485/concepts/e5b80ecc-8626-46ee-8310-1a412efe02b3

## 截图
![_20180411235808](https://user-images.githubusercontent.com/26052156/38628908-2580816c-3de5-11e8-9f86-e662b9828985.png)

## 具体描述
* 卷积图层 改为 卷积层
* 过滤 改为 过滤器

**Comment by nicoleliu42** [comment]
感谢反馈！已经修正啦
