### ISSUE TITLE
5 深度 > 7项目 > 暂时没看到内容

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#174]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/47e56df1-4278-40e4-96eb-8531d6f241d9/concepts/225e2717-1fd6-488f-8719-d91d687df7f5

## 截图
![_20180412000224](https://user-images.githubusercontent.com/26052156/38629078-9f40e294-3de5-11e8-899a-4b609a6e4c5a.png)

**Comment by UdacityShuwenLiu** [comment]
由于是测试账号，隐藏了项目提交界面，感谢理解
