### ISSUE TITLE
6. 强化学习 > 课程5：蒙特卡洛方法 >2. 迷你项目：蒙特卡洛方法 (OpenAI Gym-BlackjackEnv)>翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#175]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/0efcbe12-d803-4021-9c37-f9935046fe46

## 截图
![image](https://user-images.githubusercontent.com/5260728/38646695-8d891ff4-3e1b-11e8-87f7-85c128d1b282.png)

## 具体描述
1. “王牌可以是 11 点或 1 点，11 点时“可用”。”不知道这里的“11 点时“可用””是什么意思，翻译的很突兀，看了教材中的原文并没有这句；
2. 这本书应该翻译为《强化学习引论》，“简介”有点太简单了，不到位

**Comment by nicoleliu42** [comment]
感谢反馈~！书名已修改！
