### ISSUE TITLE
6. 强化学习 > 课程5：蒙特卡洛方法 >7. 实现>翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#179]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/0c7422ed-6f69-40b1-bae9-3a0fe2012216

## 截图
![image](https://user-images.githubusercontent.com/5260728/38661927-265c2534-3e65-11e8-858f-6559703dfb29.png)

## 具体描述
这里的“状态值”有误，根据上下文应该是“动作值”

**Comment by nicoleliu42** [comment]
感谢反馈~已经修改完毕！
