### ISSUE TITLE
markdown格式异常

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#18]
## 课程导航+地址
例子：进阶 > 强化学习 > 强化学习框架：问题 > [19. 总结](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/ee28399b-f809-4e2b-936b-5a88d7297899#)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/11350750/43597013-639f3b42-96b3-11e8-90c4-94c3eb16d49c.png">

<img width="662" alt="snipaste_2018-08-03_00-25-11" src="https://user-images.githubusercontent.com/11350750/43597118-b5d49592-96b3-11e8-8619-195c6a81f186.png">

## 具体描述
“阶段性任务”应该另起一行

“MDPs和一步动态特性”部分按照图示修改，另起一行 和 缩进

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
