### ISSUE TITLE
6. 强化学习 > 课程5：蒙特卡洛方法 >8. 迷你项目：蒙特卡洛方法（第 2 部分）>翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#180]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/efbed560-72ae-4556-abd9-9e1622fca63f

## 截图
![image](https://user-images.githubusercontent.com/5260728/38662568-5aef2fce-3e67-11e8-8b6a-a53b98a2d346.png)

## 具体描述
翻译有误，应该是4个参数

**Comment by nicoleliu42** [comment]
感谢反馈！已核实错误并在后台修改~
