### ISSUE TITLE
6. 强化学习 > 课程5：蒙特卡洛方法 > 9. 广义策略迭代 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#181]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/8bb0f6b2-de21-4d5a-9ac2-00b9049d423a

## 截图
![image](https://user-images.githubusercontent.com/5260728/38679039-4253fa8e-3e95-11e8-9ea2-f4ad6eef2e04.png)

## 具体描述
视频49秒处，“through the state's base”应该为“through the state's space”

**Comment by nicoleliu42** [comment]
感谢反馈 字幕已经修正了哦
