### ISSUE TITLE
6. 强化学习 > 课程5：蒙特卡洛方法 > 10. MC 控制：增量均值 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#182]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/352a3998-fd96-4e7a-89fb-a5d462781575

## 截图
![image](https://user-images.githubusercontent.com/5260728/38680213-4d1ca698-3e98-11e8-99ba-19993c87363e.png)

## 具体描述
视频3分40秒处，英文字幕“enter a wild loop”应该为“enter a while loop”

**Comment by nicoleliu42** [comment]
感谢反馈 字幕已经修正了哦
