### ISSUE TITLE
6. 强化学习 > 课程5：蒙特卡洛方法 > 17. 迷你项目：蒙特卡洛方法（第 3 部分） > 课程设计问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#188]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd101-cn/parts/ead4579b-dc98-4646-8c9f-6d1dd0ddafc0/modules/426ff413-d0d4-4dba-99dc-4955626bb960/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/8a50cbdb-5a91-456f-afe1-e19e8dd58167
## 截图
![image](https://user-images.githubusercontent.com/5260728/38710185-944e88d4-3ef1-11e8-871f-2ba1785136bd.png)

## 具体描述
1. notebook出现错误，文字写的是“你的算法将有三个参数”，然后下面对参数的介绍出现了四个；最后下面的函数参数又变成了三个
2. 我看了习题答案，答案中自定义了三个函数，我觉得这块设计是不是一下子跨度太大了，初学者自己根本就写不出来这三个函数的

**Comment by UdacityShuwenLiu** [comment]
好的 感谢
