### ISSUE TITLE
6. 强化学习 > 课程5：蒙特卡洛方法 > 18. MC 控制：常量 α（第 1 部分） > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#189]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/09a009ed-326b-477d-a941-9d397f9a2f02

## 截图
![image](https://user-images.githubusercontent.com/5260728/38710862-e69d18e6-3ef4-11e8-8593-c544d21e4d29.png)

## 具体描述
视频2秒处“stop”应该为“step”

**Comment by nicoleliu42** [comment]
感谢反馈 字幕已经修正啦
