### ISSUE TITLE
神经网络-第11节-技术术语(learning rate)中文翻译前后不一致

### ISSUE THREAD

**Issue by binliu-base** [udacity/mlnd-issues-zh#19]
## 课程导航+地址
进阶 > 神经网络 > [11. 感知器算法](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/d00ecaa9-56de-405d-ba6e-530b44a59836/concepts/dc837952-c0d8-43fc-921c-f1ffe316c795#)

## 截图
在第11节的页面和中文字幕中 ，此技术术语(learning rate)被翻译为学习率， 但在后面的课程中它被翻译为学习速率

#### 第11节的页面中的翻译

![nn 11 2](https://user-images.githubusercontent.com/24623272/43641236-6c00125a-9755-11e8-8af2-cb01965c03ba.PNG)

#### 第25节视频36秒处字幕的翻译

![nn 25 1](https://user-images.githubusercontent.com/24623272/43641465-5f127fb4-9756-11e8-8413-8d6e9d6e032c.PNG)

## 具体描述
建议把learning rate统一翻译为学习速率，这样更接近实际意义，也更符合行业惯例。

**Comment by sylviasun916** [comment]
已修改 感谢反馈
