### ISSUE TITLE
6. 强化学习 > 课程6：时间差分方法 > 7.TD 控制：Sarsa(0) > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#191]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/d2de57a0-cd89-40bd-b87f-ec0298b425cf/concepts/24a2e101-9cd6-4343-bd7a-814a42762e21

## 截图
![image](https://user-images.githubusercontent.com/5260728/38714980-62934676-3f0b-11e8-96be-74719617243d.png)

## 具体描述
视频1分23秒处，我听出来应该是“tuple of interaction”而不是“couple of interaction”，应该是指用到的这几个状态和动作值构成的元组

**Comment by nicoleliu42** [comment]
感谢反馈！字幕已经修正了哦
