### ISSUE TITLE
6. 强化学习 > 课程3：强化学习框架：解决方案 >6.贝尔曼方程（第1部分） > 备注问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#192]
## 课程导航+地址
6. 强化学习 > 课程3：强化学习框架：解决方案 >[6.贝尔曼方程（第1部分](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/ce8d7dbc-3320-4440-bdd3-556b8ca3fda2/concepts/3d66f062-a1a4-492f-a829-b252819844d7#)

## 截图
<img width="713" alt="2018-04-13 11 20 27" src="https://user-images.githubusercontent.com/16119486/38715288-c68d15c0-3f0c-11e8-843f-2667dcbf8218.png">

## 具体描述
建议删掉“并且”或者与下面的内容合并成一句

**Comment by UdacityShuwenLiu** [comment]
搞定
