### ISSUE TITLE
6. 强化学习 > 课程3：强化学习框架：解决方案 >11. 最优策略 > 底噪问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#193]
## 课程导航+地址
6. 强化学习 > 课程3：强化学习框架：解决方案 >[11. 最优策略](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/ce8d7dbc-3320-4440-bdd3-556b8ca3fda2/concepts/934b86fe-7f3a-4dc0-8baf-e7c597cc0ece#)

## 具体描述
视频前半段能听到明显的噪声

**Comment by UdacityShuwenLiu** [comment]
无法解决 = =
