### ISSUE TITLE
6. 强化学习 > 课程3：强化学习框架：解决方案 >12. 练习：最优策略 > 选项内容与题设不一致

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#194]
## 课程导航+地址
6. 强化学习 > 课程3：强化学习框架：解决方案 >[12. 练习：最优策略](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/ce8d7dbc-3320-4440-bdd3-556b8ca3fda2/concepts/7c1e4c72-9c0a-4e47-b74b-7352d2739682#)

## 截图
<img width="606" alt="2018-04-13 12 49 24" src="https://user-images.githubusercontent.com/16119486/38717407-55f0f8ce-3f19-11e8-8e8d-a01e438e8c20.png">

## 具体描述
建议将问题选项中“A,S+下划线+数字”改成"A,S+下表数字"

**Comment by UdacityShuwenLiu** [comment]
OK
