### ISSUE TITLE
6. 强化学习 > 课程3：强化学习框架：解决方案 >13. 贝尔曼方程（第2部分) > 窄屏适应性问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#196]
## 课程导航+地址
6. 强化学习 > 课程3：强化学习框架：解决方案 >[13. 贝尔曼方程（第2部分)](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/ce8d7dbc-3320-4440-bdd3-556b8ca3fda2/concepts/ee8e341e-e3bb-4d99-9ee1-a5910d6cfde8#)

## 截图
<img width="587" alt="2018-04-13 1 30 41" src="https://user-images.githubusercontent.com/16119486/38718336-21859206-3f1f-11e8-948d-a4a33e921b24.png">

## 具体描述
在较窄的屏幕下  公式现实不完整，且**不能横向滚动**

**Comment by UdacityShuwenLiu** [comment]
无解，感谢提供建议
