### ISSUE TITLE
6. 强化学习 > 课程3：强化学习框架：解决方案 >13. 贝尔曼方程（第 2 部分） >几个小问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#197]
## 课程导航+地址
6. 强化学习 > 课程3：强化学习框架：解决方案 >[13. 贝尔曼方程（第 2 部分）](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/ce8d7dbc-3320-4440-bdd3-556b8ca3fda2/concepts/ee8e341e-e3bb-4d99-9ee1-a5910d6cfde8)

## 截图
<img width="1030" alt="2018-04-13 1 42 34" src="https://user-images.githubusercontent.com/16119486/38718965-2ccaae0a-3f22-11e8-9170-889aa4ff64f5.png">

## 具体描述
如图所示，第一处貌似重复了，第二处应该多了个逗号

**Comment by nicoleliu42** [comment]
感谢反馈 文本已经修改~
