### ISSUE TITLE
6. 强化学习 > 课程8：项目-机器人走迷宫 > 2. 问题描述 > 链接问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#198]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/8e9d4e15-b8fb-481b-8a7f-8ae92511b599/concepts/8d23b263-d6e0-4ed6-9d6a-9442c81e9762

## 截图
![image](https://user-images.githubusercontent.com/5260728/38721235-e1dd003c-3f2b-11e8-8a64-7b5d06fb18dd.png)

## 具体描述
“这个链接”点开无效

**Comment by UdacityShuwenLiu** [comment]
已修复
