### ISSUE TITLE
6. 强化学习 > 课程9：连续空间中的强化学习 > 5. 离散化 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#199]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/7f9a6f80-b67d-4b6c-b59b-91aa2e134734/concepts/a07fda6d-c75a-4e8f-9c5c-36c2a43d0be7

## 截图
![image](https://user-images.githubusercontent.com/5260728/38722691-4a965222-3f31-11e8-8db0-e8ee8656e50c.png)

![image](https://user-images.githubusercontent.com/5260728/38722802-b8e90bc0-3f31-11e8-86f6-842a93d6e01c.png)

## 具体描述
1. 视频1分6秒处“the robot may need to void”应该为“the robot may need to avoid”
2. 视频2分6秒处“makes sense and spacial domains like gridworlds”应该为“makes sense in spacial domains like grid worlds”

**Comment by nicoleliu42** [comment]
字幕已经修正啦 感谢反馈！
