### ISSUE TITLE
4.非监督学习 > 课程 1：聚类 > 3.聚类电影 英文字幕出错

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#20]
## 课程导航+地址
4.非监督学习 > 课程 1：聚类 > 3.聚类电影 英文字幕出错（https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/bfc4f456-5bee-4c30-84a9-17559b08d0cb/modules/2ca706af-ae54-4219-907b-91ae5c3b110a/lessons/5452184060/concepts/30158685770923）

## 截图

![error_img](https://user-images.githubusercontent.com/35166778/38436818-3cb57e90-3a08-11e8-8d2b-e5612aa08753.png)

## 具体描述
视频1:46s处英文字幕(look) a the movie，需改为at the movie

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
