### ISSUE TITLE
6. 强化学习 > 课程9：连续空间中的强化学习 > 6. Tile Coding > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#200]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/7f9a6f80-b67d-4b6c-b59b-91aa2e134734/concepts/3df727fc-03e8-412a-ad35-37fe0549db26

## 截图
![image](https://user-images.githubusercontent.com/5260728/38723256-0ed67b98-3f33-11e8-96fb-9a9ce70957e5.png)

## 具体描述
视频2分16秒处 subtitles 应该为subtiles

**Comment by nicoleliu42** [comment]
感谢反馈~字幕已经修正了哦
