### ISSUE TITLE
6. 强化学习 > 课程9：连续空间中的强化学习 > 8. 函数逼近 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#201]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/7f9a6f80-b67d-4b6c-b59b-91aa2e134734/concepts/71f0d234-98fc-4a0f-8416-58f3090feec2

## 截图
![image](https://user-images.githubusercontent.com/5260728/38724807-e509b140-3f37-11e8-97fb-33abd37c9017.png)

## 具体描述
for prediction没有翻译，可以翻译为“针对预测”

**Comment by nicoleliu42** [comment]
感谢反馈哦 文本已经修正啦
