### ISSUE TITLE
6. 强化学习 > 课程9：连续空间中的强化学习 > 9. 线性函数逼近 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#202]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/7f9a6f80-b67d-4b6c-b59b-91aa2e134734/concepts/9e591e2b-11dc-4c7f-a276-e6f41f6815dc

## 截图
![image](https://user-images.githubusercontent.com/5260728/38725203-2b27b57c-3f39-11e8-8964-2ea9f52a6f4c.png)

## 具体描述
视频28秒处“数字优化”应该翻译为“数值优化”

**Comment by nicoleliu42** [comment]
感谢反馈 字幕已经修改~
