### ISSUE TITLE
非监督学习> 课程5 > 特征缩放> [11sklearn 中的最小值/最大值缩放器]>字幕排版

### ISSUE THREAD

**Issue by kinghonglee** [udacity/mlnd-issues-zh#203]
## 课程导航+地址
例子：非监督学习> 课程5 > 特征缩放> [11sklearn 中的最小值/最大值缩放器](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/bfc4f456-5bee-4c30-84a9-17559b08d0cb/modules/2ca706af-ae54-4219-907b-91ae5c3b110a/lessons/5442519605/concepts/28980485350923)

## 截图
![image](https://user-images.githubusercontent.com/31353264/38727039-7d339098-3f3e-11e8-97b8-5d22c6af7c29.png)

## 具体描述
视频00:01s处字幕最后一个单词“we”，把它放到下个字幕里面看着会整洁一些

**Comment by nicoleliu42** [comment]
感谢反馈！之后我们会调整时间轴的哦~！
