### ISSUE TITLE
6. 强化学习 > 课程10：深度Q学习 > 4. 时间差分学习 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#205]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/2faec296-1a78-4393-9aea-2b91310713ed/concepts/f9b63bf1-b4b3-4ede-9c76-e9773f879cc0

## 截图
![image](https://user-images.githubusercontent.com/5260728/38763301-48c15a88-3fcb-11e8-8983-882bd9fbf4ae.png)

## 具体描述
视频3分05秒“off policy algorithms”翻译为“新策略算法”似乎不妥，我觉得这里的翻译要斟酌下。

**Comment by nicoleliu42** [comment]
感谢反馈！已修改为“离线策略算法”
