### ISSUE TITLE
6. 强化学习 > 课程10：深度Q学习 > 9. 深度 Q 学习算法 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#206]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/2faec296-1a78-4393-9aea-2b91310713ed/concepts/10c5aa3a-b77f-4dcb-ab19-65aa119d2842

## 截图
![image](https://user-images.githubusercontent.com/5260728/38765470-aa16dbb8-3ff4-11e8-944b-426825da33ea.png)

## 具体描述
视频1分58秒处英文字幕“function pi”应为“function phi”

**Comment by nicoleliu42** [comment]
感谢反馈~字幕已经修改好 稍后会重新部署哦
