### ISSUE TITLE
6. 强化学习 > 课程3：强化学习框架：解决方案> 5.状态值函数> 英文字幕问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#217]
## 课程导航+地址
6. 强化学习 > 课程3：强化学习框架：解决方案> [5.状态值函数](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/ce8d7dbc-3320-4440-bdd3-556b8ca3fda2/concepts/0fab7f1b-5ac2-4b13-a190-8c0f78da6ef0)
## 截图
<img width="671" alt="2018-04-15 5 31 01" src="https://user-images.githubusercontent.com/16119486/38777002-0ec6cb16-40d3-11e8-945f-294bed80781a.png">

## 具体描述
视频01:09处字幕"sixt"，需改为"six"

**Comment by nicoleliu42** [comment]
字幕已经修正 稍后会重新部署 感谢反馈哦~
