### ISSUE TITLE
6. 强化学习 > 课程4：动态规划>22.值迭代 > 多个翻译问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#219]
## 课程导航+地址
6. 强化学习 > 课程4：动态规划>[22.值迭代](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/9cc18f72-766e-433e-a764-46338e09cf79/concepts/e2746ec0-8816-4be3-9ab2-94da706ebc64#)

## 截图
<img width="614" alt="2018-04-15 7 05 36" src="https://user-images.githubusercontent.com/16119486/38777753-07c5ff8c-40e0-11e8-9eb4-1e992bc82188.png">
<img width="638" alt="2018-04-15 7 05 45" src="https://user-images.githubusercontent.com/16119486/38777755-0ad62616-40e0-11e8-80c2-1c14e84029aa.png">
<img width="469" alt="2018-04-15 7 13 05" src="https://user-images.githubusercontent.com/16119486/38777832-0c845df6-40e1-11e8-9da9-eff8dd9ad79b.png">

## 具体描述
第一点（上两张截图）：02:02处整个建议改成"然后V(S)使用同样的函数,但是计算的是在π(s)的值"(重点是evaluate应该翻译成计算，而不是评估)
第二点（第三张截图）：02:10处建议将“ARGMAX处评估的函数”改成“argmax时计算出的函数值"
同时这个argmax真心感觉如此翻译有点不妥，但是我又想不出什么好的方式。

**Comment by nicoleliu42** [comment]
感谢反馈！字幕已修正 稍后会重新部署
