### ISSUE TITLE
6. 强化学习 > 课程5：蒙特卡洛方法>4.实现 >链接问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#226]
## 课程导航+地址
6. 强化学习 > 课程5：蒙特卡洛方法>[4. 实现](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/c6a9bf61-1311-4fb3-bdef-74cd7b94eacb)

## 截图
<img width="749" alt="2018-04-16 7 01 54" src="https://user-images.githubusercontent.com/16119486/38805543-c0b67e04-41a8-11e8-9ac4-91550a657559.png">

## 具体描述
这个链接，访问报404的错误

**Comment by UdacityShuwenLiu** [comment]
已修复
