### ISSUE TITLE
6.强化学习 > 课程5：蒙特卡洛方法>6.MC预测：动作值 >翻译问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#227]
## 课程导航+地址
6.强化学习 > 课程5：蒙特卡洛方法>[6.MC预测：动作值](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/193835c9-f2ea-4f4a-ad2c-142d76d8a0c6#)

## 截图
<img width="1044" alt="2018-04-16 7 07 46" src="https://user-images.githubusercontent.com/16119486/38805794-ba3adaba-41a9-11e8-973f-4054ca16a4f0.png">

## 具体描述
视频00:36s处字幕"设置"，需改为"设定"

**Comment by nicoleliu42** [comment]
感谢反馈！字幕已经修正啦 稍后会重新部署
