### ISSUE TITLE
6.强化学习 > 课程5：蒙特卡洛方法>6.MC预测：动作值 >翻译问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#228]
## 课程导航+地址
6.强化学习 > 课程5：蒙特卡洛方法>[6.MC预测：动作值](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/193835c9-f2ea-4f4a-ad2c-142d76d8a0c6#)

## 截图
<img width="778" alt="2018-04-16 7 24 39" src="https://user-images.githubusercontent.com/16119486/38806440-d4c45b84-41ab-11e8-9f32-40097032e07f.png">

## 具体描述
视频03:16处字幕"逼近"，需改为"估计"

**Comment by nicoleliu42** [comment]
感谢反馈！已经改正啦
