### ISSUE TITLE
6.强化学习 > 课程5：蒙特卡洛方法>9.广义策略迭代>翻译问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#229]
## 课程导航+地址
6.强化学习 > 课程5：蒙特卡洛方法>[9.广义策略迭代](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/8bb0f6b2-de21-4d5a-9ac2-00b9049d423a)
## 截图
<img width="990" alt="2018-04-16 7 37 09" src="https://user-images.githubusercontent.com/16119486/38807120-1d55b5f8-41ae-11e8-8223-4e4032033e55.png">

## 具体描述
视频01:20处字幕"设置"，需改为"设定"

**Comment by nicoleliu42** [comment]
感谢反馈 字幕已经修正啦 稍后会重新部署哦~！
