### ISSUE TITLE
进阶>深度学习>神经网络>11 感知器算法-编写感知器算法

### ISSUE THREAD

**Issue by wilow89** [udacity/mlnd-issues-zh#230]
进阶>4. 深度学习>1. 神经网络>11 感知器算法-编写感知器算法（练习题）
题目描述为：然后点击测试运行绘出感知器算法给出的解决方案。它实际上会画出一组虚线，显示算法如何接近最佳解决方案（用黑色实线表示）。

## 截图
![image](https://user-images.githubusercontent.com/34020359/38844291-4c17fc12-4225-11e8-8142-2efc62009d56.png)

## 具体描述
点测试答案并不能如文字描述的出图，浏览器chrome，系统mac。

**Comment by UdacityShuwenLiu** [comment]
是的，需要翻墙才可以，这个暂时无解QAQ，需求已经提到美国区了QAQ
