### ISSUE TITLE
6.强化学习 > 课程5：蒙特卡洛方法>14.练习：Epsilon 贪婪策略>选项的问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#232]
## 课程导航+地址
6.强化学习 > 课程5：蒙特卡洛方法>[14.练习：Epsilon 贪婪策略](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/945c310b-493e-4d9c-8f16-1f3d3b892cbb#)

## 截图
<img width="335" alt="2018-04-17 11 33 22" src="https://user-images.githubusercontent.com/16119486/38847239-2f55abf2-4233-11e8-842b-ab6a2f8b233d.png">
<img width="340" alt="2018-04-17 11 33 26" src="https://user-images.githubusercontent.com/16119486/38847240-2fa83bba-4233-11e8-9802-5681745cfb19.png">
<img width="321" alt="2018-04-17 11 33 28" src="https://user-images.githubusercontent.com/16119486/38847241-2ff27720-4233-11e8-94a6-c4779a369608.png">

## 具体描述
所有问题的最后一个选项都是“（5）这道题很难！正确答案是所有爱普西隆值都不满足该要求”是不是有点问题。我觉得可能只要“所有爱普西隆值都不满足该要求”就OK

**Comment by UdacityShuwenLiu** [comment]
已修复
