### ISSUE TITLE
6.强化学习 > 课程5：蒙特卡洛方法>15.练习：探索与利用 > 小问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#233]
## 课程导航+地址
6.强化学习 > 课程5：蒙特卡洛方法>[15.练习：探索与利用](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/30151e2d-760b-455e-9321-c7a8bc69a4c1)

## 截图
<img width="644" alt="2018-04-17 11 44 47" src="https://user-images.githubusercontent.com/16119486/38847586-ff9bdeca-4234-11e8-924c-7c5d3effd9ed.png">

## 具体描述
如果换行的话建议把“并且”，“并且”和“以及”去掉

**Comment by UdacityShuwenLiu** [comment]
已经修复
