### ISSUE TITLE
非监督学习> 课程8>随机投影与ICA>5、独立成分分析算法>课程资源链接

### ISSUE THREAD

**Issue by kinghonglee** [udacity/mlnd-issues-zh#234]
## 课程导航+地址
非监督学习> [课程8>随机投影与ICA>5、独立成分分析算法>课程资源链接](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/bfc4f456-5bee-4c30-84a9-17559b08d0cb/modules/2ca706af-ae54-4219-907b-91ae5c3b110a/lessons/50edc524-8ca0-460a-8ee1-d500b6c70e3e/concepts/1c3e56c4-6169-4ffa-85a5-f42c49fe4b57)

## 截图
![image](https://user-images.githubusercontent.com/31353264/38921638-d3888de8-4328-11e8-8de4-75aae5348b66.png)

## 具体描述
课程链接无法下载

**Comment by UdacityShuwenLiu** [comment]
已修复
