### ISSUE TITLE
非监督学习> 课程8>随机投影与ICA>9、[Lab 解决方案] 独立成分分析>代码

### ISSUE THREAD

**Issue by kinghonglee** [udacity/mlnd-issues-zh#235]
## 课程导航+地址
非监督学习> [课程8>随机投影与ICA>&&9、[Lab](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/bfc4f456-5bee-4c30-84a9-17559b08d0cb/modules/2ca706af-ae54-4219-907b-91ae5c3b110a/lessons/50edc524-8ca0-460a-8ee1-d500b6c70e3e/concepts/186a9f58-6df9-49c0-95e8-160e88e8dd72) 解决方案] 独立成分分析>代码
## 截图

![image](https://user-images.githubusercontent.com/31353264/38922596-2460172a-432b-11e8-940f-de0bdd97eeb1.png)
![image](https://user-images.githubusercontent.com/31353264/38923413-0f1ca76e-432d-11e8-9b95-69694fe46a71.png)
![image](https://user-images.githubusercontent.com/31353264/38924926-cb341b32-4330-11e8-9975-6724d8543f6b.png)
![image](https://user-images.githubusercontent.com/31353264/38924986-f035e1e0-4330-11e8-8c42-59a8163d128b.png)

![image](https://user-images.githubusercontent.com/31353264/38925080-26703c92-4331-11e8-93da-14d6b058b1da.png)
![image](https://user-images.githubusercontent.com/31353264/38925145-55a076c6-4331-11e8-9bec-e4f1d9319cce.png)

## 具体描述
既然上面这个有执行结果，是不是下面这一行就没有必要再显示了，以免报错！
PS：也不知道找那么多trouble，udacity会不会以后不让我体验课程了(#^.^#)

**Comment by UdacityShuwenLiu** [comment]
已修复
