### ISSUE TITLE
非监督学习> 课程8>随机投影与ICA>8、[Lab 解决方案] 独立成分分析>课程体验

### ISSUE THREAD

**Issue by kinghonglee** [udacity/mlnd-issues-zh#236]
## 课程导航+地址

非监督学习> [课程8>随机投影与ICA>[8、[lab]独立成分分析](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/bfc4f456-5bee-4c30-84a9-17559b08d0cb/modules/2ca706af-ae54-4219-907b-91ae5c3b110a/lessons/50edc524-8ca0-460a-8ee1-d500b6c70e3e/concepts/a0f09cb5-77c0-4f73-a587-f998a1af8f86#)] 独立成分分析>课程体验
## 截图

![image](https://user-images.githubusercontent.com/31353264/38925368-00ec3646-4332-11e8-9182-7c19df3571c6.png)

## 具体描述
课程打开以后是文件目录，我觉得应该指向文件

**Comment by UdacityShuwenLiu** [comment]
好的
