### ISSUE TITLE
非监督学习> 课程8>随机投影与ICA>8、[Lab ] 独立成分分析&&9、[Lab 解决方案] 独立成分分析>代码问题

### ISSUE THREAD

**Issue by kinghonglee** [udacity/mlnd-issues-zh#237]
## 课程导航+地址
非监督学习> 课程8>随机投影与ICA>[8、[Lab ] 独立成分分析](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/bfc4f456-5bee-4c30-84a9-17559b08d0cb/modules/2ca706af-ae54-4219-907b-91ae5c3b110a/lessons/50edc524-8ca0-460a-8ee1-d500b6c70e3e/concepts/a0f09cb5-77c0-4f73-a587-f998a1af8f86)&&[9、[Lab 解决方案] 独立成分分析](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/bfc4f456-5bee-4c30-84a9-17559b08d0cb/modules/2ca706af-ae54-4219-907b-91ae5c3b110a/lessons/50edc524-8ca0-460a-8ee1-d500b6c70e3e/concepts/186a9f58-6df9-49c0-95e8-160e88e8dd72)>代码问题

## 截图
![image](https://user-images.githubusercontent.com/31353264/38925575-9e04a260-4332-11e8-8863-897d48dbf5c2.png)

## 具体描述
红框中的”```python”是不是应该去掉，不然语句无法执行！

**Comment by UdacityShuwenLiu** [comment]
搞定
