### ISSUE TITLE
深度学习 > 神经网络 > 23. 对数几率回归 > 视频一中的错误

### ISSUE THREAD

**Issue by wilow89** [udacity/mlnd-issues-zh#238]
## 截图

![image](https://user-images.githubusercontent.com/34020359/38929436-d92d00ba-433e-11e8-9249-7481b5313571.png)

## 具体描述
视频26s处视频中的公式开始，公式都有点问题，需改为-log(0.6)-(log0.2)-log(0.1)-log(0.7) = 4.8，并非log(0.6)= -(log0.2)-log(0.1)-log(0.7) =4.8

**Comment by UdacityShuwenLiu** [comment]
OK搞定
