### ISSUE TITLE
6. 强化学习 > 课程5：蒙特卡洛方法 > 3. MC预测：状态值 > 翻译问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#239]
## 课程导航+地址
6. 强化学习 > 课程5：蒙特卡洛方法 > [3. MC预测：状态值](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/d29f23ea-2ecd-4b67-9d14-53849d126e12)

## 截图
![2018-04-19 2 25 02](https://user-images.githubusercontent.com/16119486/38974750-d21abda4-43dd-11e8-843d-1dcc57735407.png)
![2018-04-19 2 25 10](https://user-images.githubusercontent.com/16119486/38974753-d2f357e0-43dd-11e8-8ea3-870b4ae299e6.png)
![2018-04-19 2 25 31](https://user-images.githubusercontent.com/16119486/38974754-d3516434-43dd-11e8-891c-b22cb88f4e2a.png)

## 具体描述
建议将off-policy翻译成“异策略”，on-policy翻译成“同策略"。参考周志华《机器学习》16.4.1蒙特卡洛强化学习

**Comment by nicoleliu42** [comment]
已统一为“离线策略”与”异同策略“，感谢反馈！
