### ISSUE TITLE
翻译不准确

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#24]
## 课程导航+地址
例子：机器学习 > 强化学习 > 蒙特卡洛方法 > [3. MC 预测：状态值](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/d29f23ea-2ecd-4b67-9d14-53849d126e12#)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/11350750/43687779-2d6943a8-990e-11e8-92fc-d7800d32a67a.png">

## 具体描述
视频5m19s处字幕“经历”，需改为“访问”，而且这一术语出现了多次，希望考虑，似乎在计算机科学中visit一般被翻译成访问

**Comment by sylviasun916** [comment]
已修改 感谢反馈
