### ISSUE TITLE
6. 强化学习 > 课程5：蒙特卡洛方法 >22. 总结 > 翻译问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#240]
## 课程导航+地址
6. 强化学习 > 课程5：蒙特卡洛方法 >[22. 总结](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/8c9f974e-e90c-4136-a4e9-f8b3b697bdaf)

## 截图
![2018-04-19 2 30 46](https://user-images.githubusercontent.com/16119486/38974902-5aaed56a-43de-11e8-97ba-985e1ed77006.png)

## 具体描述
"既定策略"建议翻译成"同策略"，"新策略"建议翻译成"异策略"  参见[#239](https://github.com/udacity/mlnd-issues-zh/issues/239)

**Comment by nicoleliu42** [comment]
感谢反馈！已经修改为“同策略”和“异策略”啦！
