### ISSUE TITLE
深度学习  > 2 深度神经网络 > 7 Keras > 文字部分的错误

### ISSUE THREAD

**Issue by wilow89** [udacity/mlnd-issues-zh#241]
## 课程导航+地址
例子：深度学习  > 2 深度神经网络 > 7 Keras >文字部分的错误
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/2f907351-912b-40c7-8b2b-289e1446fa32/concepts/7c3d9b4c-206d-4430-9459-c78357181d9a

## 截图
![image](https://user-images.githubusercontent.com/34020359/39002066-4aa8e6be-442a-11e8-8539-caa6dfa54878.png)

## 具体描述
1、上下不统一
2、上面那个方法会导致练习中编译不通过，应该是写错了吧？

**Comment by UdacityShuwenLiu** [comment]
已修复
