### ISSUE TITLE
深度学习 > 2 深度神经网络 > 8 Keras Lab 准备: 录取学生 > 按照仓库中的说明设置 Conda 环境并安装必要的依赖项。

### ISSUE THREAD

**Issue by wilow89** [udacity/mlnd-issues-zh#242]
## 课程导航+地址
例子：进阶 > 经典街机游戏克隆 > 编写readme文档 > [1. 欢迎](教室地址链接)

## 截图
![image](https://user-images.githubusercontent.com/34020359/39032869-f68b2290-44a1-11e8-8962-1c777546e9a7.png)
![image](https://user-images.githubusercontent.com/34020359/39032881-02db04ac-44a2-11e8-8cd6-a00e2ff9481a.png)

## 具体描述
按照github的配置，配置后，打开jupyter notebook运行ipy文件时，kernel启动不起来，会出现以下错误
KernelRestarter: restarting kernel (2/5)
/Users/LeiWang/.pyenv/versions/anaconda3-5.0.1/envs/aind-dl/bin/python: No module named ipykernel_launcher

请在github中增加一条，如果出现这个错误：terminal中再输入ipython3 kernel install
方可正常运行

**Comment by UdacityShuwenLiu** [comment]
搞定
