### ISSUE TITLE
深度学习 > 2 深度神经网络 > 8 Keras Lab 准备: 录取学生 > 文字描述

### ISSUE THREAD

**Issue by wilow89** [udacity/mlnd-issues-zh#243]
## 课程导航+地址
例子：
深度学习 > 2 深度神经网络 > 8 Keras Lab 准备: 录取学生 > 文字描述
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/2f907351-912b-40c7-8b2b-289e1446fa32/concepts/bb1f6b73-b886-4ed5-ba63-a992faf7d873

## 截图
![image](https://user-images.githubusercontent.com/34020359/39033194-7ffae9f6-44a3-11e8-8904-c30bdf6fa244.png)

## 具体描述
文字：接下来，我们可以做的一件事就是为每一四个等级制作一张图。
改为：接下来，我们可以做的一件事就是为每一个rank（等级）制作一张图，共四个等级，四张图。

**Comment by nicoleliu42** [comment]
感谢反馈！文本已经修正！
