### ISSUE TITLE
深度学习 > 2 深度神经网络 > 11 早期停止 > 字幕错误

### ISSUE THREAD

**Issue by wilow89** [udacity/mlnd-issues-zh#244]
## 课程导航+地址
例子：深度学习 > 2 深度神经网络 > 11 早期停止 > 字幕错误
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/2f907351-912b-40c7-8b2b-289e1446fa32/concepts/6ca15486-4db4-4731-89f3-06b704ef8455

## 具体描述
视频40s处字幕“绿色区域”，需改为“蓝色区域”

**Comment by nicoleliu42** [comment]
感谢反馈！已核实修改！
