### ISSUE TITLE
6. 强化学习 > 课程6：时间差分方法>8. 实现 > 翻译问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#245]
## 课程导航+地址
6. 强化学习 > 课程6：时间差分方法>[8. 实现](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/d2de57a0-cd89-40bd-b87f-ec0298b425cf/concepts/f27a2426-3620-43a2-8284-f3bc476634e0#)

## 截图
![2018-04-21 1 17 01](https://user-images.githubusercontent.com/16119486/39064651-ce499f0e-4501-11e8-8bdf-30b0e420cf5a.png)

## 具体描述
把‘以及’去掉

**Comment by nicoleliu42** [comment]
感谢反馈~！
