### ISSUE TITLE
6. 强化学习 > 课程6：时间差分方法>10. TD控制：sarsamax > 中英字幕问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#246]
## 课程导航+地址
6. 强化学习 > 课程6：时间差分方法>[10. TD控制：sarsamax](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/d2de57a0-cd89-40bd-b87f-ec0298b425cf/concepts/619930e9-2973-4d28-8aef-f73e8284f343#) 

## 截图
![2018-04-21 12 26 16](https://user-images.githubusercontent.com/16119486/39062677-d14b394e-44fa-11e8-9b08-0c28445d7d84.png)

## 具体描述
00:22出现的TDC在0.5倍速率下都没明显地听到，建议确认下这边是否有‘TDC'这个东西。

**Comment by nicoleliu42** [comment]
麻烦 @UdacityShuwenLiu 确认一下这里是不是有TDC这个概念哦，我听着感觉是“it”

**Comment by UdacityShuwenLiu** [comment]
@nicoleliu42 同意，改成it吧，辛苦你

**Comment by nicoleliu42** [comment]
已修改~！
