### ISSUE TITLE
6. 强化学习 > 课程6：时间差分方法>10. TD控制：sarsamax > 链接问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#247]
## 课程导航+地址
6. 强化学习 > 课程6：时间差分方法>[10. TD控制：sarsamax](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/d2de57a0-cd89-40bd-b87f-ec0298b425cf/concepts/619930e9-2973-4d28-8aef-f73e8284f343#)

## 截图
![2018-04-21 12 41 23](https://user-images.githubusercontent.com/16119486/39063231-e6f0f066-44fc-11e8-8834-17b18f30c308.png)

## 具体描述
下面的“研究论文”打开需要翻墙

**Comment by UdacityShuwenLiu** [comment]
已修复
