### ISSUE TITLE
6. 强化学习 > 课程6：时间差分方法 > 16.分析性能 > 几个小问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#248]
## 课程导航+地址
6. 强化学习 > 课程6：时间差分方法 > [16.分析性能](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/d2de57a0-cd89-40bd-b87f-ec0298b425cf/concepts/7d2dafe6-e522-4a8d-beb0-e9dd6eadddfc)

## 截图
![2018-04-21 1 18 47](https://user-images.githubusercontent.com/16119486/39064703-04c87b0e-4502-11e8-9acb-41014fe8fb94.png)

![2018-04-21 1 05 29](https://user-images.githubusercontent.com/16119486/39064242-6172f5e8-4500-11e8-8b81-b39825f1cc11.png)

## 具体描述
红色：请看[#240](https://github.com/udacity/mlnd-issues-zh/issues/240)
绿色：建议删了

**Comment by nicoleliu42** [comment]
感谢反馈！已统一为离线策略和异同策略
