### ISSUE TITLE
6. 强化学习 > 课程9：连续空间中的强化学习>2.资源 > 链接问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#249]
## 课程导航+地址
6. 强化学习 > 课程9：连续空间中的强化学习>[2.资源](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/7f9a6f80-b67d-4b6c-b59b-91aa2e134734/concepts/7508ac67-a221-447d-b8bd-e9baaf381956#)

## 截图
<img width="510" alt="2018-04-23 4 22 52" src="https://user-images.githubusercontent.com/16119486/39114843-993c1f0e-4712-11e8-983f-4a182eb7695c.png">

## 具体描述
“OpenAI Gym文档”貌似无法打开。

**Comment by UdacityShuwenLiu** [comment]
无解 = =
