### ISSUE TITLE
字幕有错别字

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#25]
## 课程导航+地址
例子：机器学习 > 强化学习 > 蒙特卡洛方法 > [9. 广义策略迭代](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/8bb0f6b2-de21-4d5a-9ac2-00b9049d423a#)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/11350750/43688058-628573bc-9914-11e8-8968-bda5c281135a.png">

## 具体描述
视频40s处字幕“阶段”，需改为“截断”

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
