### ISSUE TITLE
6. 强化学习 > 课程9：连续空间中的强化学习 > 8.函数逼近 > 英文字幕问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#250]
## 课程导航+地址
6. 强化学习 > 课程9：连续空间中的强化学习 > [8.函数逼近](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/7f9a6f80-b67d-4b6c-b59b-91aa2e134734/concepts/71f0d234-98fc-4a0f-8416-58f3090feec2)

## 截图
![2018-04-24 1 17 45](https://user-images.githubusercontent.com/16119486/39142628-caa3c1e6-475d-11e8-84f1-e0b80fa64f3d.png)

## 具体描述
02:33处“produce a scholar”中的"scholar"建议确认一下，因为根据上下文来理解的话，应该是"produce a scalar"，前文提到了如下的内容，感觉突然出现一个scholar很奇怪。
![2018-04-24 1 17 58](https://user-images.githubusercontent.com/16119486/39142755-1af8ee28-475e-11e8-8aaf-0488ca8e2594.png)

**Comment by nicoleliu42** [comment]
感谢反馈！这里确实是scalar！
