### ISSUE TITLE
6. 强化学习 > 课程10：深度Q学习 > 5.Q学习 > 链接问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#253]
## 课程导航+地址
6. 强化学习 > 课程10：深度Q学习 > [5.Q学习](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/2faec296-1a78-4393-9aea-2b91310713ed/concepts/b0f459db-00d1-4bc7-bf67-0c4dab3c9fcd#)

## 截图
<img width="550" alt="2018-04-24 10 09 32" src="https://user-images.githubusercontent.com/16119486/39162344-a63f86b0-47a7-11e8-9755-87770d779e7e.png">

## 具体描述
"《大规模内核机器的随机特征》" 404

**Comment by UdacityShuwenLiu** [comment]
已修复 感谢
