### ISSUE TITLE
6.强化学习 > 课程10：深度Q学习 > 7.经验回放 > 翻译问题 

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#255]
## 课程导航+地址
6.强化学习 > 课程10：深度Q学习 > [7.经验回放](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/2faec296-1a78-4393-9aea-2b91310713ed/concepts/0fbb4781-9019-47ea-a494-e5e758b48867)
## 截图
![2018-04-24 6 15 54](https://user-images.githubusercontent.com/16119486/39181268-b23139ca-47eb-11e8-867e-1b9e7097c7d2.png)

## 具体描述
06:06 robust建议翻译成“鲁棒”

**Comment by nicoleliu42** [comment]
感谢反馈！第一次知道这个形容词呢 ><
