### ISSUE TITLE
6.强化学习 > 课程11:策略梯度 > 2.为何要使用基于策略的方法> 翻译问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#256]
## 课程导航+地址
6.强化学习 > 课程11:策略梯度 > [2.为何要使用基于策略的方法](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/aeceac62-e015-41ae-9fef-41551ad8b756/concepts/d8ac869a-dd97-4e57-8c8d-e87ecbb0ccc3)

## 截图
![2018-04-24 8 49 53](https://user-images.githubusercontent.com/16119486/39187983-4e0a01e6-4801-11e8-98e1-599ef0140d40.png)

## 具体描述
02:34“最右”->“最优"

**Comment by nicoleliu42** [comment]
字幕已经修正啦 感谢反馈哦！
