### ISSUE TITLE
6.强化学习 > 课程11.策略梯度 > 3.策略函数逼近 > 翻译问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#258]
## 课程导航+地址
6.强化学习 > 课程11.策略梯度 > [3.策略函数逼近](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/aeceac62-e015-41ae-9fef-41551ad8b756/concepts/bad0e0ad-f444-4285-bc06-72f0f6266066) 

## 截图
![2018-04-24 10 13 37](https://user-images.githubusercontent.com/16119486/39192922-e8568d0e-480c-11e8-8424-bc98fdece780.png)

## 具体描述
01:07 这边应该是 “离散动作空间”

**Comment by nicoleliu42** [comment]
感谢反馈！字幕已修正~！
