### ISSUE TITLE
7.毕业项目 > 1.撰写开题报告/2.毕业项目准备 > 内容重复

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#259]
## 课程导航+地址
7.毕业项目 > [1.撰写开题报告](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/30cdb6b1-2bd8-4b07-ab9f-949e9333e527/modules/ef316eb0-d5b0-4fd9-b7c2-1eb206d7c38d/lessons/84366905-264f-48c0-a365-f1709f4fdb4f/concepts/9604779c-c55d-49c0-8ede-3a23e57f4099)
7.毕业项目 > [2.毕业项目准备](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/30cdb6b1-2bd8-4b07-ab9f-949e9333e527/modules/ef316eb0-d5b0-4fd9-b7c2-1eb206d7c38d/lessons/94464a43-ebab-4747-971e-300038c4bde1/concepts/55028685390923)

## 截图

![2018-04-24 11 39 36](https://user-images.githubusercontent.com/16119486/39198458-ba1e28cc-4819-11e8-8550-b357240d9f38.png)
![2018-04-24 11 39 26](https://user-images.githubusercontent.com/16119486/39198483-ca94e448-4819-11e8-9871-9765eaee83b4.png)

## 具体描述
“毕业项目准备”貌似包含了“撰写开题报告”的所有内容

**Comment by UdacityShuwenLiu** [comment]
是的，放两遍是怕学生忘记哈哈哈，其实是2个项目，但是我把项目隐藏了
