### ISSUE TITLE
没有对应的中文翻译

### ISSUE THREAD

**Issue by DingHe** [udacity/mlnd-issues-zh#26]
##进阶 > 支持向量址 > 7.边际误差 > [7.边际误差03:26](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/8d730f6a-a6cd-4f71-af39-04edf78e6994/modules/2e02ddf2-65f6-45f9-b1e9-85a146885d68/lessons/9fa75921-e39c-4c29-b591-bc4241fa2063/concepts/91012d46-a863-4a79-aa4d-bd4d4784fe3a)

## 具体描述
视频03:26时间处没有中文翻译字幕
which means the line is too closer.

**Comment by sylviasun916** [comment]
@UdacityShuwenLiu HI shuwen 由于我打不开链接，可不可以将视频的YouTube 链接发给我一下？ 我去查一下哦，感谢！

**Comment by sylviasun916** [comment]
字幕格式问题 已修改 感谢反馈
