### ISSUE TITLE
Markdown格式异常

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#3]
## 课程导航+地址
例子：进阶 > 强化学习 > 欢迎学习强化学习 > [2. 应用](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/2942b8b9-76c1-451d-879c-3d31d3ac00c8/concepts/c8974789-7cf4-4138-9486-e11640995033#)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/11350750/43561096-036c32ae-9648-11e8-8194-33da416bfd64.png">

## 具体描述
markdown格式异常，需将后面的链接整合进前面的 “论文”

**Comment by UdacityShuwenLiu** [comment]
感谢反馈，已修复！谢谢你～
