### ISSUE TITLE
模型选择 > 通过学习曲线检测过拟合和欠拟合

### ISSUE THREAD

**Issue by Matanley** [udacity/mlnd-issues-zh#32]
## 课程导航+地址
进阶 > 机器学习基础 > 模型选择 >  [6. 通过学习曲线检测过拟合和欠拟合](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/eba65c23-416a-4876-bc82-3001ab152e32/concepts/c1d77b32-2c63-4cf3-ab9b-3c07470df57c)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/20906247/43699936-65fcfee2-9983-11e8-9a0a-7a7a0ccff2e7.png">

<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/20906247/43700336-ce70a20c-9984-11e8-9d1b-d53b602627fc.png">

## 具体描述
练习中字幕“正常”，应改为“正合适”
练习中模型名称“对数几率回归”，应改为“逻辑回归”

**Comment by Matanley** [comment]
这个练习的答案部分，即第七节的翻译也应该改成 “逻辑回归” 以实现术语的统一

![image](https://user-images.githubusercontent.com/20906247/43700807-8d7563d0-9986-11e8-9ba7-0d42c2f6d3eb.png)

**Comment by UdacityShuwenLiu** [comment]
Logistic Regression的标准翻译是“对数几率回归”（参考西瓜书），这里会confuse的话，之后会考虑全部替换为“Logistic Regression”。谢谢反馈！

**Comment by Matanley** [comment]
好的，我也学习到了，主要是课程里很多处都是用的“逻辑回归”，只有个别地方用的是“对数几率回归”，那从术语统一的角度换成哪个都没问题的，选定一个就好，不容易造成混乱，直接用英文也不错。
