### ISSUE TITLE
1.欢迎学习机器学习 > 课程1：欢迎来到机器学习纳米学位 > 你将挑战的实战项目>英文字幕+翻译问题

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#33]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/3fae39bc-fc81-4237-a940-26f58baa3036/modules/8e0a1613-be4a-4b49-bad2-cbc46a203039/lessons/28389e50-05a5-4674-8079-20f299af614a/concepts/5baa205d-2218-4644-a391-9b0b8c2a2a33

## 截图
![default](https://user-images.githubusercontent.com/35166778/38454243-02a7396c-3a96-11e8-80d1-afd80b0d702a.png)

## 具体描述
视频31s处英文字幕SIKAT learn，需改为scikit-learn
视频31s处翻译中sklearn回归，需改为scikit learn 和回归算法（因为scikit learn是一个库并不是回归算法）

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
