### ISSUE TITLE
1.欢迎学习机器学习 > 课程1：欢迎来到机器学习纳米学位 > 你将挑战的实战项目>翻译问题

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#34]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/3fae39bc-fc81-4237-a940-26f58baa3036/modules/8e0a1613-be4a-4b49-bad2-cbc46a203039/lessons/28389e50-05a5-4674-8079-20f299af614a/concepts/5baa205d-2218-4644-a391-9b0b8c2a2a33

## 截图

![default](https://user-images.githubusercontent.com/35166778/38454490-f7500b98-3a9a-11e8-9387-e2f898638d7b.png)

## 具体描述
视频40s处字幕监督式学习，需改为监督学习，从而使得翻译匹配

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！ 在部署中
