### ISSUE TITLE
1.欢迎学习机器学习 > 课程1：欢迎来到机器学习纳米学位 > 截止日期说明>链接问题

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#35]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/3fae39bc-fc81-4237-a940-26f58baa3036/modules/8e0a1613-be4a-4b49-bad2-cbc46a203039/lessons/28389e50-05a5-4674-8079-20f299af614a/concepts/9959fd96-c2bd-4e1e-94ba-cc222cf6daf8

## 截图
![default](https://user-images.githubusercontent.com/35166778/38454679-3c6e784c-3a9e-11e8-99a9-ec2fa80e5069.png)

## 具体描述
该部分的课程当中的两个链接均为Google的，需要科学上网才能成功登上。

**Comment by UdacityShuwenLiu** [comment]
已删去
