### ISSUE TITLE
1.欢迎学习机器学习 > 课程1：欢迎来到机器学习纳米学位 >社区规则>链接问题 

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#36]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/3fae39bc-fc81-4237-a940-26f58baa3036/modules/8e0a1613-be4a-4b49-bad2-cbc46a203039/lessons/28389e50-05a5-4674-8079-20f299af614a/concepts/c24019d1-37eb-4c2e-80f3-ec52e8f142c6

## 截图
![default](https://user-images.githubusercontent.com/35166778/38454908-8b727e26-3aa2-11e8-9bbe-5554bb3836ee.png)

## 具体描述
截图当中的两个链接，第一个美国的需要梯子才能登入，第二个可以直接登入不过耗时长

**Comment by UdacityShuwenLiu** [comment]
已将这部分隐藏
