### ISSUE TITLE
6. 强化学习 > 课程1：欢迎学习强化学习！ >1. 简介>链接问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#37]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/2942b8b9-76c1-451d-879c-3d31d3ac00c8/concepts/5241f281-16f4-47d5-9545-e992d4df889b

## 截图
![image](https://user-images.githubusercontent.com/5260728/38455245-fcc3a708-3aa7-11e8-9c43-4d69dfaf4825.png)

## 具体描述
所提供的“Atari Breakout”需要翻墙才能访问

**Comment by UdacityShuwenLiu** [comment]
好的
