### ISSUE TITLE
6. 强化学习 > 课程1：欢迎学习强化学习！ >2. 应用>链接问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#38]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/2942b8b9-76c1-451d-879c-3d31d3ac00c8/concepts/c8974789-7cf4-4138-9486-e11640995033

## 截图
![image](https://user-images.githubusercontent.com/5260728/38455303-df306f04-3aa8-11e8-8754-aed83065c553.png)

## 具体描述
共有三个链接存在问题，无法访问
1. 了解指导仿真机器人如何行走的研究。
2. 了解无人驾驶车强化学习。
3. 阅读这篇介绍库存管理强化学习的论文。

**Comment by UdacityShuwenLiu** [comment]
搞定
