### ISSUE TITLE
6. 强化学习 > 课程1：欢迎学习强化学习！ >3. 设置>翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#39]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/2942b8b9-76c1-451d-879c-3d31d3ac00c8/concepts/77ce71e4-1e97-4596-ae85-27b72b7357a6

## 截图
![image](https://user-images.githubusercontent.com/5260728/38455433-932cdb86-3aaa-11e8-8c2a-65da282e7861.png)

![image](https://user-images.githubusercontent.com/5260728/38455436-a487c8e6-3aaa-11e8-84f1-909cb6c02038.png)

## 具体描述
视频1分27秒处，根据上下文，这里不应该是weight，应该是wait

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
