### ISSUE TITLE
字幕错误（包括中英）

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#4]
## 课程导航+地址
例子：进阶 > 强化学习 > 欢迎学习强化学习 > [4. OpenAI Gym](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/2942b8b9-76c1-451d-879c-3d31d3ac00c8/concepts/c5ee748d-f8c3-43b8-a175-0e2ba438a2e0#)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/11350750/43561558-1c6e0488-964a-11e8-9ad7-14e7f3db96ec.png">

## 具体描述
视频1s处字幕XXXX OpenAI *agent*/ xxxx OpenAI *智能体*，需改为OpenAI Gym

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
