### ISSUE TITLE
6. 强化学习 > 课程1：欢迎学习强化学习！ >4. OpenAI Gym>翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#40]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/2942b8b9-76c1-451d-879c-3d31d3ac00c8/concepts/c5ee748d-f8c3-43b8-a175-0e2ba438a2e0

## 截图
![image](https://user-images.githubusercontent.com/5260728/38455469-3d744552-3aab-11e8-9252-7dfb6f09f03b.png)

## 具体描述
”理论知识非常数值得学习“，翻译有误，多了个”数“字

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
