### ISSUE TITLE
6. 强化学习 > 课程1：欢迎学习强化学习！ >5. 资源>链接问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#41]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/2942b8b9-76c1-451d-879c-3d31d3ac00c8/concepts/e2c22bbc-590b-4ab5-96e1-fb4f99702c45

## 截图
![image](https://user-images.githubusercontent.com/5260728/38455514-eaae8642-3aab-11e8-9d0d-cd393a37f3e6.png)

## 具体描述
所提供的教科书连接在无梯子情况下无法访问

**Comment by UdacityShuwenLiu** [comment]
已解决
