### ISSUE TITLE
markdown有误

### ISSUE THREAD

**Issue by silencehero** [udacity/mlnd-issues-zh#42]
## 截图

<img width="309" alt="image" src="https://user-images.githubusercontent.com/20534739/43763556-98d20ca6-9a5d-11e8-9d17-8e9b4ae58d74.png">

<img width="944" alt="image" src="https://user-images.githubusercontent.com/20534739/43763607-bfa492c2-9a5d-11e8-9752-c879ae391d7e.png">

## 具体描述
图1，此处代码异常，应该删除“```python”。

图2，此段代码无意义。我发现解决方案中代码执行的结果以代码的形式呈现，容易歧义。建议把解决方案换成html格式的，这样也不会轻易被更改，可读性也更好。

**Comment by UdacityShuwenLiu** [comment]
已经解决，感谢反馈！
