### ISSUE TITLE
图片重复

### ISSUE THREAD

**Issue by silencehero** [udacity/mlnd-issues-zh#43]
## 截图

<img width="544" alt="image" src="https://user-images.githubusercontent.com/20534739/43766200-6a2e653c-9a64-11e8-904c-e73cd0e68b22.png">

## 具体描述
在这个页面中，图片大部分都重复了，不知是不是刻意为之，建议删除，保留一张即可。

**Comment by UdacityShuwenLiu** [comment]
是故意为之，因为要把结果展示给学员看哦～谢谢反馈
