### ISSUE TITLE
翻译不当

### ISSUE THREAD

**Issue by silencehero** [udacity/mlnd-issues-zh#44]
## 截图
<img width="666" alt="image" src="https://user-images.githubusercontent.com/20534739/43766535-43ef577c-9a65-11e8-885b-9d33a0289d06.png">

<img width="295" alt="image" src="https://user-images.githubusercontent.com/20534739/43766650-9b472a18-9a65-11e8-8d2e-75fd14ccd28a.png">

## 具体描述
图1，这部分的翻译有点不通。
图2，侧边栏的“练习”重复了两次。

**Comment by UdacityShuwenLiu** [comment]
第二个问题已解决，感谢反馈

**Comment by sylviasun916** [comment]
@UdacityShuwenLiu  HI shuwen, 可以看一下第一个从学科专业角度，应该怎么修改比较好吗？ 谢谢！

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
