### ISSUE TITLE
 1.欢迎来到机器学习>课程2：什么是机器学习？>支持向量机 SVM 答案>翻译问题 

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#44]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/3fae39bc-fc81-4237-a940-26f58baa3036/modules/8e0a1613-be4a-4b49-bad2-cbc46a203039/lessons/b435ded8-95bc-4c97-91b1-5cdea1e4581a/concepts/2f00b649-10ab-4caa-adf6-be57d1367ab7

## 截图
![default](https://user-images.githubusercontent.com/35166778/38456210-872e4306-3ab4-11e8-8756-1a6448b29c03.png)

![default](https://user-images.githubusercontent.com/35166778/38456242-1c0a75b2-3ab5-11e8-8a62-56e4594127da.png)

## 具体描述
视频58s处字幕它都碧蓝色的线，需改为它都比蓝色的线
视频1:04处字幕一个时间仅仅能够处理一件事，需改为一次仅仅能够处理一件事/一段时间仅仅能够处理一件事

**Comment by sylviasun916** [comment]
已修改 在部署中 谢谢反馈！
