### ISSUE TITLE
字幕翻译不统一

### ISSUE THREAD

**Issue by silencehero** [udacity/mlnd-issues-zh#46]
## 截图

<img width="919" alt="image" src="https://user-images.githubusercontent.com/20534739/43771273-4423a516-9a71-11e8-8a6b-d98648613ac9.png">

<img width="725" alt="image" src="https://user-images.githubusercontent.com/20534739/43771447-da8e1194-9a71-11e8-9b79-6cb9817d0a09.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/20534739/43771238-20964720-9a71-11e8-847b-938feca04ebb.png">

## 具体描述
字幕中关于 Adjusted Rand Score和Adjusted Rand Index的翻译有点迷惑。

**Comment by sylviasun916** [comment]
已统一修改 感谢反馈！
