### ISSUE TITLE
1.欢迎来到机器学习>课程2：什么是机器学习？>神经网络>翻译问题 （语义不通）

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#46]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/3fae39bc-fc81-4237-a940-26f58baa3036/modules/8e0a1613-be4a-4b49-bad2-cbc46a203039/lessons/b435ded8-95bc-4c97-91b1-5cdea1e4581a/concepts/9556c8b3-6593-49b3-a44d-ef83febc6447

## 截图
![default](https://user-images.githubusercontent.com/35166778/38456487-b7114b60-3ab7-11e8-8b44-4c79d96fede5.png)
![default](https://user-images.githubusercontent.com/35166778/38456543-58dc5066-3ab8-11e8-8a8a-2c314f01893e.png)
![default](https://user-images.githubusercontent.com/35166778/38456605-da911f24-3ab8-11e8-913f-dd949ac3df86.png)

## 具体描述
视频2:06处字幕取出每个问题作为一个小的笔记，语义不通！怀疑是英文字幕也不正确，结合神经网络这一部分的内容，很可能原英文单词是node（节点），也与后面的叙述相对应起来。
视频3:41处字幕 然后检查是否相关的点在特定的直线上还是下，需改为  然后检查相关的点在特定的直线上还是下
视频4:30处字幕 是否相对应的点的坐标在线的上方还是下方，需改为  相对应的点的坐标在线的上方还是下方

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！在部署中
