### ISSUE TITLE
6. 强化学习 > 课程2：强化学习框架：问题 >1. 简介>翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#55]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/a3fde5d4-c811-4e8b-bc98-40c83493e80e

## 截图
![image](https://user-images.githubusercontent.com/5260728/38460939-103a1318-3af7-11e8-8a36-38d6c2b11065.png)

## 具体描述
视频12秒处及之后将“conversation”翻译为“比喻”，貌似不对，应该是“讨论”

**Comment by sylviasun916** [comment]
已修改 谢谢！
