### ISSUE TITLE
监督学习>课程1.12 均方误差与总平方误差>公式书写问题

### ISSUE THREAD

**Issue by weilansdxk** [udacity/mlnd-issues-zh#57]
## 课程导航+地址
例子：课程1 >12均方误差与总平方误差 > 公式书写问题 > https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/8d730f6a-a6cd-4f71-af39-04edf78e6994/modules/2e02ddf2-65f6-45f9-b1e9-85a146885d68/lessons/c3bb570a-0e06-4cb3-b888-9c3e6e986ea2/concepts/fba8dd74-5e19-4d6d-b8af-f5a6580e7870

## 截图
<img width="1212" alt="demo" src="图片地址">
![2](https://user-images.githubusercontent.com/31512598/38461667-0cd111a6-3b09-11e8-9571-c68d605521d8.jpg)

## 具体描述
求和符号公式还是尽量写成正规的形式，例如：
![058](https://user-images.githubusercontent.com/31512598/38461682-304e0e68-3b09-11e8-9c07-1498db4e4d31.jpg)
具体字幕翻译不是很懂，但是word中方法应该是插入新运算符中的常用运算符（第二个），然后修改成自己的字母符号。

**Comment by UdacityShuwenLiu** [comment]
好的 谢谢反馈👍
