### ISSUE TITLE
翻译不当

### ISSUE THREAD

**Issue by silencehero** [udacity/mlnd-issues-zh#58]
## 截图
<img width="873" alt="image" src="https://user-images.githubusercontent.com/20534739/43823951-4c7100e4-9b23-11e8-86a1-4f5026b3c7a5.png">

## 具体描述
视频1m09s处字幕权重，需改为体重。根据前边的练习这里是计算体重，翻译成权重是不对的。该视频中多处都是翻译成权重。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
