### ISSUE TITLE
4.非监督学习 > 课程 1：聚类 > 12.K-均值聚类可视化 3>翻译错误

### ISSUE THREAD

**Issue by kinghonglee** [udacity/mlnd-issues-zh#58]
4.非监督学习 > 课程 1：聚类 > 12.K-均值聚类可视化 3>翻译错误
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/bfc4f456-5bee-4c30-84a9-17559b08d0cb/modules/2ca706af-ae54-4219-907b-91ae5c3b110a/lessons/5452184060/concepts/30759585930923

## 截图
![image](https://user-images.githubusercontent.com/31353264/38461738-a9f5d1d2-3b0a-11e8-9228-fe23ad123d0b.png)

## 具体描述
视频00:07s处字幕“统一点”，需改为“均匀分布”

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
