### ISSUE TITLE
训练与测试模型 - 第9节 - 2:19 - 字幕错误

### ISSUE THREAD

**Issue by Matanley** [udacity/mlnd-issues-zh#6]
## 课程导航+地址
进阶 > 训练与测试模型> [9. 测试你的模型](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/318fc61b-fd70-43b7-a4e2-a3ed92719589/concepts/5c0c3f6b-753d-4e8a-bec1-4a1e26b60067)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/20906247/43566611-998b540e-9661-11e8-88a8-4803cb9a6f02.png">

## 具体描述
视频2：19s处字幕“两套集合”，需改为“两个数据集”

**Comment by sylviasun916** [comment]
已修改 感谢反馈
