### ISSUE TITLE
1.欢迎学习机器学习>课程2 什么是机器学习>17 k均值聚类>翻译问题

### ISSUE THREAD

**Issue by lonelytechreader** [udacity/mlnd-issues-zh#60]
## 课程导航+地址
例子：进阶 >1.欢迎学习机器学习>课程2 什么是机器学习>17 k均值聚类>翻译问题
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/3fae39bc-fc81-4237-a940-26f58baa3036/modules/8e0a1613-be4a-4b49-bad2-cbc46a203039/lessons/b435ded8-95bc-4c97-91b1-5cdea1e4581a/concepts/8728d646-261a-4d2d-b06f-701de0dd85c0
## 截图
<img width="1212" alt="demo" src="图片地址">

![qq 20180408092711](https://user-images.githubusercontent.com/38041963/38461953-17e6776e-3b10-11e8-868b-44e19f368154.jpg)
![qq 20180408093727](https://user-images.githubusercontent.com/38041963/38461975-93d4d640-3b10-11e8-87ac-a6aeb0bdf276.jpg)

## 具体描述
视频32s处字幕“顶住”，需改为“盯住”
视频1min6s处字幕“里”，需改为“离”

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
