### ISSUE TITLE
什么是机器学习-第二节-字幕翻译改善

### ISSUE THREAD

**Issue by GarroshPeng** [udacity/mlnd-issues-zh#61]
## 课程导航+地址
欢迎学习机器学习 > 什么是机器学习  > [2.决策树](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/3fae39bc-fc81-4237-a940-26f58baa3036/modules/8e0a1613-be4a-4b49-bad2-cbc46a203039/lessons/b435ded8-95bc-4c97-91b1-5cdea1e4581a/concepts/3f5957b3-8c03-4ec9-8619-e5dbff41de01)

## 截图
<img width="1212"  src="https://user-images.githubusercontent.com/14797875/43844551-9b2b5fc0-9b5c-11e8-91fd-ded239907107.png"  />

## 具体描述
视频22s处中文字幕"以及他们记录"，建议改成“对于这六个人中的每一个人，我们记录了他们的信息”

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
