### ISSUE TITLE
5.深度学习  > 神经网络 > 7.感知器 > 缺少中英字幕+翻译

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#65]
## 5.深度学习  > 神经网络 > 7.感知器 
教室链接：https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/d00ecaa9-56de-405d-ba6e-530b44a59836/concepts/6ba9c9eb-2e36-4b03-9bcc-01e71260a024
## 截图 1
![2under1](https://user-images.githubusercontent.com/26052156/38463024-fa4f15a4-3b22-11e8-8383-dd57f23c75f6.png)
## 具体描述
视频1分33s处字幕'**two under one**'，应改为**’two and one**'
另外这个部分只有中文和英文 没有中-英字幕
## 截图 2
![default](https://user-images.githubusercontent.com/26052156/38463076-096a598a-3b24-11e8-8dc3-932527f833ef.png)
## 具体描述
视频1分35s的**偏差单位**，英文对应的是**bias**，建议翻译成’**偏差项**‘

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
