### ISSUE TITLE
5.深度学习 > 神经网络 > 17.one-hot编码 > 字幕翻译

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#66]
## 5.深度学习 > 神经网络 > 17.one-hot编码 
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/d00ecaa9-56de-405d-ba6e-530b44a59836/concepts/cac0e3d6-38c1-4eb6-8440-4325b44703b3

## 截图
![onehot](https://user-images.githubusercontent.com/26052156/38463090-bfe36c74-3b24-11e8-82ff-2f8aa74578f4.png)
## 具体描述
视频01：17s处字幕’**热码编码**‘，建议统一为**one-hot编码**。

**Comment by sylviasun916** [comment]
建议已采纳，在修改中，谢谢反馈！
