### ISSUE TITLE
5.深度学习 > 1.神经网络 > 1-11内容与监督学习里的感知器算法内容重复

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#67]
## 5.深度学习 > 1.神经网络  vs 3.监督学习 > 2.感知器算法 
教室链接：
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/d00ecaa9-56de-405d-ba6e-530b44a59836/concepts/dc837952-c0d8-43fc-921c-f1ffe316c795
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/8d730f6a-a6cd-4f71-af39-04edf78e6994/modules/2e02ddf2-65f6-45f9-b1e9-85a146885d68/lessons/2ec5353c-3ca0-4e01-b6f0-29ab0d452d37/concepts/6ba9c9eb-2e36-4b03-9bcc-01e71260a024

## 截图
![default](https://user-images.githubusercontent.com/26052156/38463110-633ff860-3b25-11e8-8054-3f3d983930ec.png)

## 具体描述
大量视频重复

**Comment by UdacityShuwenLiu** [comment]
建议还是保留着～～觉得两个part都需要这些内容
