### ISSUE TITLE
5.深度学习 > 1.神经网络 > 24.梯度下降 > 公式标注

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#69]
## 5.深度学习 > 1.神经网络 > 24.梯度下降 
教室地址：https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/d00ecaa9-56de-405d-ba6e-530b44a59836/concepts/0d92455b-2fa0-4eb8-ae5d-07c7834b8a56

## 截图
![xij](https://user-images.githubusercontent.com/26052156/38463729-86e758cc-3b33-11e8-9173-44d43d3c37bd.png)

## 具体描述
关于x的上下标i,j问题：
* 建议第一句改为“如果有m个样本点，标记为...”。
* 上下标混乱，公式里的i 应该统一标注为上标要跟下面的下标j区分开，这样比较清楚些。并且在最后能注明（i=1,....m）
* 第二句改为"我们的目标是计算E在 单个样本点x时的梯度，其中x包含n个特征，即x=(x1..xn)
* 之后的公式里的代表j的数字和j应该统一改成下标的方式。并注明(j = 1,..,n)

**Comment by UdacityShuwenLiu** [comment]
搞定 非常感谢！
