### ISSUE TITLE
训练与测试模型 - 第10节 - 翻译错误

### ISSUE THREAD

**Issue by Matanley** [udacity/mlnd-issues-zh#7]
## 课程导航+地址
例子：进阶 > 训练与测试模型 > [10. 练习：在 sklearn 中进行测试](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/318fc61b-fd70-43b7-a4e2-a3ed92719589/concepts/0ebede2d-a9a4-4191-86b6-81c1feb016a8)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/20906247/43566939-bab32b42-9662-11e8-99f3-3a112d77c241.png">

## 具体描述
翻译“我们使用 25% 的点”，需改为“我们使用 25% 的数据”

**Comment by UdacityShuwenLiu** [comment]
已修复，感谢反馈！
