### ISSUE TITLE
练习答案出现无效代码

### ISSUE THREAD

**Issue by INEEDanORANGE** [udacity/mlnd-issues-zh#70]
## 截图
![image](https://user-images.githubusercontent.com/32951816/43891115-25c28fa2-9bfb-11e8-88ba-219a8032250b.png)

## 具体描述
答案文档出现大量废代码

**Comment by UdacityShuwenLiu** [comment]
我这里好像是正常的，是不是显示问题呀，谢谢你的反馈～
