### ISSUE TITLE
4.非监督学习 > 课程 3：层次聚类法与密度聚类 >1. K-均值聚类>翻译问题

### ISSUE THREAD

**Issue by kinghonglee** [udacity/mlnd-issues-zh#71]
4.非监督学习 > 课程 3：层次聚类法与密度聚类 >[1. K-均值聚类](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/bfc4f456-5bee-4c30-84a9-17559b08d0cb/modules/2ca706af-ae54-4219-907b-91ae5c3b110a/lessons/ff204bbc-7426-41ab-b832-6e7f382a9939/concepts/539930cc-e03d-46db-85d4-1db2b0400660)
## 截图

![image](https://user-images.githubusercontent.com/31353264/38465028-75a7c75c-3b49-11e8-83ab-d23ac4e895c2.png)

## 具体描述
视频13s处字幕“它能帮你从几乎任何数据集中提取模式”，需改为“它几乎能帮你从任何数据中提取模式”

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
