### ISSUE TITLE
4.非监督学习 > 课程 3：层次聚类法与密度聚类 >1. K-均值聚类>字幕问题

### ISSUE THREAD

**Issue by kinghonglee** [udacity/mlnd-issues-zh#72]
## 课程导航+地址
4.非监督学习 > 课程 3：层次聚类法与密度聚类 >[1. K-均值聚类](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/bfc4f456-5bee-4c30-84a9-17559b08d0cb/modules/2ca706af-ae54-4219-907b-91ae5c3b110a/lessons/ff204bbc-7426-41ab-b832-6e7f382a9939/concepts/539930cc-e03d-46db-85d4-1db2b0400660)
## 截图

![image](https://user-images.githubusercontent.com/31353264/38465176-67ae0114-3b4b-11e8-900d-aa66efddbd58.png)

## 具体描述
视频33s处字幕“我相信你能 K-均值聚类方法也能做到”，需改为"我相信你能， K-均值聚类方法也能做到"
ps：就是中间加了个逗号！

**Comment by sylviasun916** [comment]
谢谢反馈，我这边暂时换了个说法， 已修改。

逗号没有加 是因为我们中文字幕保持统一的符号风格哦 谢谢
