### ISSUE TITLE
缺少工作区

### ISSUE THREAD

**Issue by INEEDanORANGE** [udacity/mlnd-issues-zh#72]
## 截图
![image](https://user-images.githubusercontent.com/32951816/43967099-32ce8d80-9cf6-11e8-84e1-eb3fff22d947.png)

## 具体描述
未提供工作区

**Comment by UdacityShuwenLiu** [comment]
原课程中是包含工作区的哦，因为内测账号不能提交项目，所以关闭了工作区。感谢你的反馈❤️
