### ISSUE TITLE
 2.机器学习基础>课程 1：培训与测试模型>统计学知识复习>可能是 链接问题

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#73]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/318fc61b-fd70-43b7-a4e2-a3ed92719589/concepts/5677da97-a610-4127-92ed-c41e13548c8f

## 截图
![default](https://user-images.githubusercontent.com/35166778/38465524-5bc739f2-3b4f-11e8-95ef-8da562fb9411.png)

## 具体描述
在“课外部分”这一文字描述部分，感觉是应该有链接指示到有相关知识点的地方，但是没有，只有加粗的字体。

**Comment by UdacityShuwenLiu** [comment]
已修复
