### ISSUE TITLE
文档翻译有误

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#73]
## 课程导航+地址
例子：进阶 > 强化学习 > 蒙特卡洛方法 > [22.总结](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/8c9f974e-e90c-4136-a4e9-f8b3b697bdaf#)

## 截图
<img width="661" alt="snipaste_2018-08-12_13-08-02" src="https://user-images.githubusercontent.com/11350750/43998789-deb03dac-9e30-11e8-8478-dd0f22240edb.png">

## 具体描述
“异同策略”，需改为“在线策略”

**Comment by sylviasun916** [comment]
已修改 感谢反馈
