### ISSUE TITLE
2.机器学习基础>课程 1：培训与测试模型>在 Pandas 中加载数据>翻译描述出错

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#74]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/318fc61b-fd70-43b7-a4e2-a3ed92719589/concepts/0fdcf21e-19f2-4e1d-a9b9-e8f73c8cbda4

## 截图
![default](https://user-images.githubusercontent.com/35166778/38465554-c54ed6fa-3b4f-11e8-9748-9fb564f6d294.png)

![default](https://user-images.githubusercontent.com/35166778/38465568-e7133c0e-3b4f-11e8-97e1-7734ba87aac3.png)

## 具体描述
可以看到，第一张截图的内容是   点击“测试运行” 然而在下面的三个可点击的框（如第二张截图所示）并没有“测试运行”这一选项！应该改为“测试答案”！

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
