### ISSUE TITLE
      2.机器学习基础>课程 1：培训与测试模型>Numpy 数组>课程设计问题

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#75]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/318fc61b-fd70-43b7-a4e2-a3ed92719589/concepts/4c706530-12a9-46ca-889f-92941b0883e5

## 截图
![default](https://user-images.githubusercontent.com/35166778/38465850-573a5e06-3b53-11e8-8291-427922b4f16c.png)
![default](https://user-images.githubusercontent.com/35166778/38465855-6046b33c-3b53-11e8-9a29-ce2acf7f9df0.png)

## 具体描述
如图所示，第一张截图是没有问题的，问题在接下来的截图当中的图表，如果说是与前面内容相关的，那么就不应该是截出来这样的图表。于是，根据接下来的练习，我判断是不是课程内容少了一部分--因为练习当中有需要将两个特征提取出来作为一个Numpy数组，也就是变量X。所以应该是课程内容少了！！！

**Comment by UdacityShuwenLiu** [comment]
是的，已经补充上去啦，感谢
