### ISSUE TITLE
5.深度学习>1.神经网络>26&27.Lab梯度下降 >翻译+公式

### ISSUE THREAD

**Issue by casper5300** [udacity/mlnd-issues-zh#76]
## 5.深度学习>1.神经网络>26.Lab准备梯度下降
教室地址：
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/c1f8edbc-be9c-4481-8e9a-340b4749d401/modules/16167855-110f-4d34-9c8d-79c5bfe60135/lessons/d00ecaa9-56de-405d-ba6e-530b44a59836/concepts/64f025bd-1d7b-42fb-9f13-8559242c1ec9#
## 截图 1
![default](https://user-images.githubusercontent.com/26052156/38464036-542e01dc-3b39-11e8-9e9a-72ede36d65e4.png)
## 截图2
![2](https://user-images.githubusercontent.com/26052156/38464043-632245ea-3b39-11e8-86ef-c41b32515d8d.png)
## 具体描述
渐变改为梯度

## 截图 3
![lab](https://user-images.githubusercontent.com/26052156/38464046-7ee183b8-3b39-11e8-8278-a0410f8cd109.png)
## 具体描述
根据课程里的公式，这里加号应改为减号。但如果按减号写代码提交是错误的。
如果要用减号要将(y-yhat)改为(yhat-y) ，建议与前面的视频保持一致。
前面视频公式问题已经另一个贴中提出

**Comment by sylviasun916** [comment]
1. 翻译已修改，谢谢反馈！

2. @UdacityShuwenLiu  同学对于练习中公式的反馈，麻烦你看一下哦，评估一下需不需要修改。

**Comment by UdacityShuwenLiu** [comment]
搞定
