### ISSUE TITLE
文档有小错

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#76]
## 课程导航+地址
例子：进阶 > 强化学习 > 蒙特卡洛方法 > [15. 探索与利用](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/30151e2d-760b-455e-9321-c7a8bc69a4c1)

## 截图

![img_0129](https://user-images.githubusercontent.com/11350750/43999334-fb288b5e-9e3c-11e8-9405-0cb6eea985ae.jpg)

## 具体描述
标红地方1：收敛 改为 收敛于
标红地方2：去掉 为

**Comment by UdacityShuwenLiu** [comment]
感谢反馈！
