### ISSUE TITLE
4.非监督学习 > 课程 3：层次聚类法与密度聚类 >3. 层次聚类与密度聚类>翻译问题

### ISSUE THREAD

**Issue by kinghonglee** [udacity/mlnd-issues-zh#78]
## 课程导航+地址
4.非监督学习 > 课程 3：层次聚类法与密度聚类 >3. 层次聚类与密度聚类>[翻译问题](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/bfc4f456-5bee-4c30-84a9-17559b08d0cb/modules/2ca706af-ae54-4219-907b-91ae5c3b110a/lessons/ff204bbc-7426-41ab-b832-6e7f382a9939/concepts/50c65b18-9956-4b05-8b5d-383dcfb193bb)
## 截图

![image](https://user-images.githubusercontent.com/31353264/38466803-3b893a16-3b61-11e8-8244-edf39a7215e2.png)

## 具体描述
视频20s处字幕“特点”，需改为“特征”

**Comment by sylviasun916** [comment]
已修改 谢谢反馈 在部署中
