### ISSUE TITLE
6. 强化学习 > 课程2：强化学习框架：问题 >16. 练习：一步动态特性（第 2 部分）>翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#79]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/55ed22d2-2bfc-4a31-91ab-a812d7d02467

## 截图
![image](https://user-images.githubusercontent.com/5260728/38467554-cf3c6ab6-3b6c-11e8-98ec-083acf143488.png)

## 具体描述
翻译有误，“下个时间步是电量很高的概率为 30%”应为“下个时间步是电量很低的概率为 30%”

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
