### ISSUE TITLE
评估指标 - 第1-2节 - 混淆矩阵 - 字幕错误

### ISSUE THREAD

**Issue by Matanley** [udacity/mlnd-issues-zh#8]
## 课程导航+地址
进阶 > 评估指标  > [1. 混淆矩阵](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/e1850d27-a3d0-4a76-a021-1719ce34245f/concepts/2034dd12-8ffc-4753-b8f4-c6042487ea5d)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/20906247/43567240-b7b5e492-9663-11e8-934f-18bf1b87f609.png">

## 具体描述
**第一节**
视频49s处字幕“真正”，需改为“真阳性”
视频57s处字幕“真负”，需改为“真阴性”
视频01:06s处字幕“假负”，需改为“假阴性”
视频01:19s处字幕“假正”，需改为“假阳性”
视频01:31s处字幕“真正”，需改为“真阳性”
视频01:37s处字幕“假负”，需改为“假阴性”
视频01:42s处字幕“假正”，需改为“假阳性”
视频01:46s处字幕“真负”，需改为“真阴性”
视频02:01s处字幕“真正”，需改为“真阳性”
视频02:04s处字幕“假负”，需改为“假阴性”
视频02:11s处字幕“假正”，需改为“假阳性”
视频02:16s处字幕“真负”，需改为“真阴性”

**第二节**
视频4s处字幕“真正”，需改为“真阳性”
视频6s处字幕“正”，需改为“阳性”
视频11s处字幕“真负”，需改为“真阴性”; "负“ 需改为”阴性“
视频14s处字幕“负”，需改为“阴性”
视频00:19s处字幕“假正”，需改为“假阳性”; "实际为负”需改为“实际为阴性”
视频00:21s处字幕“正”，需改为“阳性”
视频00:28s处字幕“假负”，需改为“假阴性”
视频00：31s处字幕“负”，需改为“阴性”

抱歉我强迫症犯了

**Comment by Matanley** [comment]
这一节练习部分也需要改同样的错误。
![image](https://user-images.githubusercontent.com/20906247/43567837-98bd46f0-9665-11e8-9229-67e0e430045b.png)

**Comment by Matanley** [comment]
第 6 节 及 第 7 节同样存在类似的问题，不知是否可以直接替换这些字幕？

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
