### ISSUE TITLE
6. 强化学习 > 课程2：强化学习框架：问题 >17. MDP（第3部分）>翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#80]
## 课程导航+地址
例子：进阶 > 经典街机游戏克隆 > 编写readme文档 > [1. 欢迎](教室地址链接)

## 截图
![image](https://user-images.githubusercontent.com/5260728/38467718-f7cc8590-3b6e-11e8-8412-77b934055179.png)

## 具体描述
视频1分15秒处“short-sighted”应当翻译为“目光短浅的，短视的”，所以我觉得这里翻译成“预测能力”不是很贴切。

**Comment by sylviasun916** [comment]
short-sighted 直译是这样，不过这里还是意译比较好。已修改为 “否则 智能体会出现看不清故障的情况”  谢谢反馈！
