### ISSUE TITLE
6. 强化学习 > 课程2：强化学习框架：问题 >19. 总结 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#81]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/ee28399b-f809-4e2b-936b-5a88d7297899

## 截图
![image](https://user-images.githubusercontent.com/5260728/38467926-70de048e-3b71-11e8-92b2-c2f86cc5b7f2.png)

## 具体描述
“马克尔夫决策流程 (MDP)”应当翻译为“马尔可夫决策过程（MDP）”

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
