### ISSUE TITLE
6. 强化学习 > 课程3：强化学习框架：解决方案 >2. 策略 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#83]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/ce8d7dbc-3320-4440-bdd3-556b8ca3fda2/concepts/766ed227-4ac9-4a91-b8e6-e4d37bfdf2b9

## 截图
![image](https://user-images.githubusercontent.com/5260728/38468207-6b3c97a8-3b75-11e8-9a82-367eae7c4766.png)

## 具体描述
视频3分1s处，英文字母有误，少了一个we，应该是“we will explore”

**Comment by sylviasun916** [comment]
已修改 谢谢反馈 ！ 在部署中
