### ISSUE TITLE
 2.机器学习基础>课程 1：培训与测试模型>在 sklearn 中训练模型>翻译问题+练习无法生成图像（在没有梯子下）

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#84]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/318fc61b-fd70-43b7-a4e2-a3ed92719589/concepts/9ed98cab-aa00-43a3-b8dc-ef7ed0bee156

## 截图
![default](https://user-images.githubusercontent.com/35166778/38468333-c0dd8662-3b76-11e8-9802-1f992db30708.png)
![default](https://user-images.githubusercontent.com/35166778/38468331-bb69c650-3b76-11e8-9df0-5d7c0e4ccf5c.png)
![default](https://user-images.githubusercontent.com/35166778/38468434-68e87c3a-3b78-11e8-8187-3e09a8a0a421.png)

## 具体描述
1. 第一张截图当中的“测试结果”应该是翻译自原英文“test run”，但是下面的三个按钮里面与之对应的是“测试答案”
2.如第二张截图所示，选择了分类器之后，按下测试答案后并没有出现分好类的图片。
3.补充第二点：在搭上梯子之后，成功得出图像！因此是需要科学上网才能看到分割线的。

**Comment by sylviasun916** [comment]
1. 已修改，已显示在教室中。 

2 和 3 需要 @UdacityShuwenLiu  看一下哦，谢谢

**Comment by UdacityShuwenLiu** [comment]
是的 需要翻墙才可以 已经跟美国区提了需求 感谢反馈👍
