### ISSUE TITLE
字幕翻译不准确

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#85]
## 课程导航+地址
例子：机器学习 > 强化学习 > 深度强化学习 > [1. 深度强化学习](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/7f9a6f80-b67d-4b6c-b59b-91aa2e134734/concepts/a96517cc-a316-43ac-a7ea-51c339c072c2#)

## 截图
![image](https://user-images.githubusercontent.com/11350750/44022611-b003c7ae-9f1a-11e8-90c2-e4ca651ff107.png)

## 具体描述
视频1m41s处字幕 “马尔科夫特性”，需改为 “马尔科夫性”，专有名词

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
