### ISSUE TITLE
字幕翻译不通顺

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#86]
## 课程导航+地址
例子：机器学习（进阶） > 强化学习 > 连续空间中的强化学习 > [6. Tiling Code](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/7f9a6f80-b67d-4b6c-b59b-91aa2e134734/concepts/3df727fc-03e8-412a-ad35-37fe0549db26#)

## 截图
![image](https://user-images.githubusercontent.com/11350750/44046980-b5fec042-9f5f-11e8-9fe3-fa501a26c5f9.png)

## 具体描述
视频2m37s处字幕，需改为 “最终得到一个基于空间复杂程度的状态空间的划分。”

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
