### ISSUE TITLE
2.机器学习基础>课程 1：培训与测试模型>手动调整参数>翻译问题+课程描述有误+需要梯子才能出现练习图像

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#86]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/318fc61b-fd70-43b7-a4e2-a3ed92719589/concepts/d7f3ec93-ab4e-463b-947d-47779ab4bbed

## 截图
![default](https://user-images.githubusercontent.com/35166778/38468803-7d501b38-3b7d-11e8-9c7f-d31a52a60872.png)
![default](https://user-images.githubusercontent.com/35166778/38468811-9e1162aa-3b7d-11e8-99a8-cb88e7506439.png)

![default](https://user-images.githubusercontent.com/35166778/38468565-d671b738-3b7a-11e8-82e7-b38916c20c2d.png)
![default](https://user-images.githubusercontent.com/35166778/38468667-199f884a-3b7c-11e8-8e11-c42d32fab7b7.png)

## 具体描述
1.练习中最后出现的图像需要梯子才能显现！第一张是没梯子的情况，第二张是有梯子的。

2.翻译的太多了，这部分的内容的英文有一部分是根本不需要翻译的！因为是用来调试SVC的参数的，翻译成中文反而让人难以看懂。或许可以在这部分给出官方文档的[链接](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC)(看这里的官方文档，C惩罚系数和gamma并不是整形的，是浮点型的)------或许是课程设计的画图不能实现浮点型？？

应改为：
kernel:  ‘linear’  (线性), ‘poly’ （多项式）, ‘rbf’（高斯核）
degree（整型）：多项式内核的次数（如果选择了多项式内核）
gamma （浮点型）：γ 参数
C（浮点型）：C 参数

**Comment by sylviasun916** [comment]
2. 翻译已修正，已采纳建议保留一部分英文。 即时显示在教室内。 

@UdacityShuwenLiu  SHUWEN 可不可以看一下这位同学的其他反馈，对课程优化有没有可以借鉴之处？谢谢，如果优化完，之后可以 CLOSE 该 ISSUE 哦。

**Comment by UdacityShuwenLiu** [comment]
感谢反馈，目前无法解决图片显示问题，我们会继续跟进
