### ISSUE TITLE
代码多引用

### ISSUE THREAD

**Issue by NancyLele** [udacity/mlnd-issues-zh#87]
## 课程导航+地址
机器学习基础 >课程1：训练与测试模型 > 在sklearn中训练模型
## 截图
![issue_1](https://user-images.githubusercontent.com/7942270/44067599-e68ab970-9fa8-11e8-8236-4d62b373ac36.png)

## 具体描述
测试代码中引用了GradientBosstingClassifier,但是上下文中并未出现这个模型

**Comment by UdacityShuwenLiu** [comment]
感谢反馈，已修复
