### ISSUE TITLE
2.机器学习基础>课程 1：培训与测试模型>练习：在 sklearn 中进行测试>翻译错误+需要梯子才能出现练习图像 

### ISSUE THREAD

**Issue by noctisplus** [udacity/mlnd-issues-zh#88]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/ae5a94f8-9fe7-4d42-90df-b5081349e6a2/modules/af100a8f-0ee4-4211-906d-872b186b2edc/lessons/318fc61b-fd70-43b7-a4e2-a3ed92719589/concepts/0ebede2d-a9a4-4191-86b6-81c1feb016a8

## 截图
![default](https://user-images.githubusercontent.com/35166778/38469802-f2843830-3b8c-11e8-8855-1177de59496a.png)
![default](https://user-images.githubusercontent.com/35166778/38469803-fd37ebb4-3b8c-11e8-902d-388d1c244d8b.png)
![default](https://user-images.githubusercontent.com/35166778/38469805-0565f7f4-3b8d-11e8-9291-24bbab75607a.png)

## 具体描述
1. 同样，下面的按钮中并没有出现“测试运行”，需改为“测试答案”
2. 练习的结果需要科学上网才能出现，否则是没有图像的

**Comment by sylviasun916** [comment]
1. 已修改，保持与按钮一致，谢谢反馈！ 即时显示在教室内。 

2. @UdacityShuwenLiu 麻烦看一下是什么情况哦，如果可以修改完，可以 close 该 issue 哦，谢谢

**Comment by UdacityShuwenLiu** [comment]
是的，出现图片的问题暂时无解，已经跟美国区提了需求，感谢反馈👍
