### ISSUE TITLE
评估指标 - 第7节 - 字幕错误

### ISSUE THREAD

**Issue by Matanley** [udacity/mlnd-issues-zh#9]
## 课程导航+地址
例子：进阶 > 评估指标  > [7. 答案 - 假负例与假正例](教室地址链接)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/20906247/43568917-87b2ccf6-9668-11e8-81d6-4607b3c38c27.png">

## 具体描述
标题“答案 - 假负例与假正例”需改为“假阴性与假阳性”
视频28s处字幕，需删除 =

**Comment by sylviasun916** [comment]
字幕已修改 感谢反馈
