### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by NancyLele** [udacity/mlnd-issues-zh#90]
## 课程导航+地址
机器学习进阶>课程2评估指标>精度

## 截图

![issue_4](https://user-images.githubusercontent.com/7942270/44067905-3fffc3b4-9faa-11e8-99ea-6167b411088b.png)

## 具体描述
精度，精度翻译错误，是55.6%，但是翻译成了55.7%

**Comment by sylviasun916** [comment]
已修改  感谢反馈！
