### ISSUE TITLE
字幕翻译不准确，术语前后不一致

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#91]
## 课程导航+地址
例子：进阶 > 强化学习 > deep Q-learning > [4. 时间差分学习](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/2faec296-1a78-4393-9aea-2b91310713ed/concepts/f9b63bf1-b4b3-4ede-9c76-e9773f879cc0#)

## 截图
![image](https://user-images.githubusercontent.com/11350750/44152128-3e52f03a-a0d7-11e8-83c3-696f68b35b30.png)

## 具体描述
视频41s处字幕 调整数值函数，需改为 调整值函数

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
