### ISSUE TITLE
6. 强化学习 > 课程2：强化学习框架：问题>13.MDP（第1部分) > 翻译问题+字幕问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#91]
## 课程导航+地址
进阶 > 6. 强化学习 > 课程2：强化学习框架：问题>[13.MDP(第1部分)](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/3240a1ff-2cae-4917-90b1-d7c5c5f75a92#)

<img width="896" alt="2018-04-09 12 46 06" src="https://user-images.githubusercontent.com/16119486/38469980-6d98dff6-3b8f-11e8-9698-20bb24728435.png">
<img width="626" alt="2018-04-09 12 46 30" src="https://user-images.githubusercontent.com/16119486/38469987-77fa88aa-3b8f-11e8-874b-ded53261355a.png">

## 具体描述
视频01:56处字幕"脚本S"，需改为"手写体S"。
建议英文字幕中将“ Script S"连在一起，而不要分开

**Comment by sylviasun916** [comment]
已修改 在部署中 谢谢指正
