### ISSUE TITLE
6. 强化学习 > 课程2：强化学习框架：问题>16.练习：一步动态特性 > 建议使用英文 

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#92]
## 课程导航+地址
进阶 >6. 强化学习 > 课程2：强化学习框架：问题>[16.练习：一步动态特性](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/55ed22d2-2bfc-4a31-91ab-a812d7d02467#)

## 截图
<img width="378" alt="2018-04-09 1 04 14" src="https://user-images.githubusercontent.com/16119486/38470232-645cc8fa-3b92-11e8-8cd0-ac7b52dc693b.png">

## 具体描述
这边建议使用英文，上方状态图和上面的两道题目都是英文

**Comment by nicoleliu42** [comment]
感谢反馈！已修改完毕！
