### ISSUE TITLE
6. 强化学习 > 课程2：强化学习框架：问题>18.有限MDP> 链接问题

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#93]
## 课程导航+地址
进阶 > 6. 强化学习 > 课程2：强化学习框架：问题>[18.有限MDP](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/ded16999-b166-4fe7-aa98-02cbfea07ba8#)

## 截图
<img width="622" alt="2018-04-09 1 24 35" src="https://user-images.githubusercontent.com/16119486/38470423-165c823c-3b95-11e8-87f9-1b8aeb417c13.png">

## 具体描述
“OpenAI Gym 文档”的链接访问非常非常非常非常慢，几乎打不开

**Comment by UdacityShuwenLiu** [comment]
收到，但是无解，感谢提供建议
