### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#94]
## 课程导航+地址
例子：进阶 > 强化学习 > deep Q-learning > [7. 经验回放](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/2faec296-1a78-4393-9aea-2b91310713ed/concepts/0fbb4781-9019-47ea-a494-e5e758b48867)

## 截图
<img width="720" alt="snipaste_2018-08-16_00-46-55" src="https://user-images.githubusercontent.com/11350750/44160782-1a609d00-a0ee-11e8-8520-3e91b5d49f6b.png">

## 具体描述
文件链接失效（无VPN状态）

**Comment by UdacityShuwenLiu** [comment]
已修复，感谢！
