### ISSUE TITLE
6. 强化学习 > 课程3：强化学习框架：解决方案 >2. 策略 > 没有中文字幕

### ISSUE THREAD

**Issue by LonerSkywalker** [udacity/mlnd-issues-zh#94]
## 课程导航+地址
6. 强化学习 > 课程3：强化学习框架：解决方案 >[2. 策略](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/ce8d7dbc-3320-4440-bdd3-556b8ca3fda2/concepts/66559240-49b2-492a-ae1d-b2d9eb844814)

## 截图
<img width="524" alt="2018-04-09 1 53 59" src="https://user-images.githubusercontent.com/16119486/38470666-f0774184-3b98-11e8-951e-c80500388a78.png">

## 具体描述
01:12开始一句话没有中文字幕

**Comment by sylviasun916** [comment]
字幕文件格式出错，已修改 在部署中 谢谢指正！
