### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#95]
## 课程导航+地址
例子：进阶 > 强化学习 > deep Q-learning > [8. 固定Q目标](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/2faec296-1a78-4393-9aea-2b91310713ed/concepts/46221098-2ac2-4981-b639-99f0af698e96)

## 截图
<img width="720" alt="snipaste_2018-08-16_00-57-56" src="https://user-images.githubusercontent.com/11350750/44161280-6f50e300-a0ef-11e8-8065-4bfaf493bab5.png">

## 具体描述
youtube链接打不开

**Comment by UdacityShuwenLiu** [comment]
已提示学生，感谢反馈！
