### ISSUE TITLE
链接无效

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#96]
## 课程导航+地址
例子：进阶 > 强化学习 > deep Q-learning > [9. 深度Q学习算法](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/2faec296-1a78-4393-9aea-2b91310713ed/concepts/10c5aa3a-b77f-4dcb-ab19-65aa119d2842#)

## 截图
<img width="720" alt="snipaste_2018-08-16_00-59-23" src="https://user-images.githubusercontent.com/11350750/44161349-a58e6280-a0ef-11e8-8fda-83632f99cc56.png">

## 具体描述
链接打不开（无VPN）

**Comment by UdacityShuwenLiu** [comment]
不翻墙状态好像是可以打开的哦～谢谢反馈！
