### ISSUE TITLE
6. 强化学习 > 课程3：强化学习框架：解决方案 >8. 最优性 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#96]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/ce8d7dbc-3320-4440-bdd3-556b8ca3fda2/concepts/a025fcb0-526a-485e-aba7-84a2c273dd7b

## 截图
![image](https://user-images.githubusercontent.com/5260728/38473273-d805bc76-3bbf-11e8-97c2-89bc1b21e599.png)
![image](https://user-images.githubusercontent.com/5260728/38473278-e4219156-3bbf-11e8-96af-b52f2e19ea8f.png)

## 具体描述
有两处问题：
1. 1分4秒处“in the grid role”似有误，根据上下文这里应该是“in the grid world”，在网格世界中
2. 2分10秒处“MBP”应为“MDP”，3分8秒处出现同样问题，3分10秒处出现同样问题；

**Comment by sylviasun916** [comment]
已核实修改 在部署中 谢谢反馈！
