### ISSUE TITLE
字幕翻译不准确

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#97]
## 课程导航+地址
例子：进阶 > 强化学习 > 策略梯度 > [7. 受限策略梯度](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/aeceac62-e015-41ae-9fef-41551ad8b756/concepts/c832f0c8-a830-4fe7-895c-bc163a028af2#)

## 截图
![image](https://user-images.githubusercontent.com/11350750/44266488-4f3f3200-a25d-11e8-83a5-b906264f3b7b.png)

## 具体描述
视频3m12s处字幕翻译不准确，需改为“我们需要想出一个用到不同动作的概率分布的策略”

**Comment by sylviasun916** [comment]
已修改 感谢反馈
