### ISSUE TITLE
字幕中有错别字

### ISSUE THREAD

**Issue by yangjjie94** [udacity/mlnd-issues-zh#98]
## 课程导航+地址
例子：进阶 > 强化学习 > 行动者-评论者方法 > [5. 优势函数](https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/0d858969-d716-4991-9cb5-bc7c5bdb7500/lessons/d34af204-cf9d-457d-9967-4b22163d8363/concepts/0dfc0717-d94e-4a1b-95ae-962e229356de#)

## 截图
![image](https://user-images.githubusercontent.com/11350750/44270823-1d34cc80-a26b-11e8-8b1f-29d666700f31.png)

## 具体描述
视频1m10s处字幕 “方程”，需改为“方差”

**Comment by sylviasun916** [comment]
已修改 感谢反馈
