### ISSUE TITLE
6. 强化学习 > 课程3：强化学习框架：解决方案 >13. 贝尔曼方程（第 2 部分） > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/mlnd-issues-zh#99]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd009-cn-advanced/parts/2bbf8d86-29ff-49e4-b355-ff9c7a1f66a5/modules/b6dc8e19-e92e-4d26-9b75-ac1ca6447580/lessons/ce8d7dbc-3320-4440-bdd3-556b8ca3fda2/concepts/ee8e341e-e3bb-4d99-9ee1-a5910d6cfde8

## 截图
![form](https://user-images.githubusercontent.com/5260728/38474307-9ae30dac-3bcf-11e8-9dab-cae5f4c39841.PNG)

## 具体描述
这个地方form不应该翻译成“表单”，应该翻译成“形式”或者“式子”

**Comment by sylviasun916** [comment]
已修改 谢谢反馈！
